mate-desktop/caja

src/caja-file-management-properties.ui
Setting a default windows size fixes that the preferences window display always to huge with GTK3.
Expanding list colums avoid to use a scrollbar for a few entries.
=> U fixes for file management preferences

src/caja-window.c
This reduce the size of the statusbar that it looks like GTK2 version.
The size can now controled with .frame.flat and/or .flat.button selector
by the theme.
=> GTK3: set top and bottom margin of statusbar to zero

src/caja-places-sidebar.c
taken from upstream commits:
https://git.gnome.org/browse/nautilus/commit/?id=cda2c75df4b95a481e8b774081ec1240d47fa45f
https://git.gnome.org/browse/nautilus/commit/?id=4764a856c7a6e5a84d4067e7b105c09a93ffdbe4
@flexiondotorg: fixes https://bugs.launchpad.net/bugs/1377967
=> [1.8] places-sidebar: fix crash

src/caja-application.c, src/caja-application.h
This pull request should fix https://github.com/mate-desktop/caja/issues/398 without causing g_bus_unwatch_name_assertion. Merely based on nautilus commits. Please review. Thanks
=> Fix automount on locked screen

src/caja-places-sidebar.c
- drag a folder to the top or bottom of the bookmark list to add
a new bookmark. a horizontal line will be shown and the mouse
pointer will have a '+' at its right side.
- if there are no bookmarks (and that section isn't shown), drag
a folder over the network section's heading. this will add a new
bookmark and make the bookmarks list visible.
- drag a file or a folder over some existing bookmark to move it
into the bookmarked folder. the mouse pointer will have an arrow
at its right side.
- if you want to copy a file or a folder there instead, perform
the same operation but hold ctrl during that. the mouse pointer
will have a '+' at its right side. no horizontal line will be
shown, so you will be able to distinguish this operation from
adding a new bookmark. :)
adapted from …
=> places-sidebar: enable both creating bookmarks and dropping files

eel/eel-editable-label.c
this fixes non selected text if renaming a file
taken from:
https://git.gnome.org/browse/nautilus/commit/?h=gnome-3-0&id=d2c3410
=> GTK3: editable-label : only clear the selection if we change to insensitive

libcaja-private/caja-icon-container.c
however, now it will auto-scroll to the left if you manually
scroll to the right and then click on any filename. I presume
this behavior is more desired than the previous one. if it's
not so, let me know (in the comments).
adapted from
https://github.com/linuxmint/nemo/commit/72c2214c82637ab622438d46c28e67289a49d472
(thanks to @glebihan)
fixes https://github.com/mate-desktop/caja/issues/406
@flexiondotorg @NiceandGently @stefano-k 
It works fine in GTK+2 build in Debian Testing, but I'd like to get it tested more before merging (e.g. GTK+3 build, other distros, etc.) :smile:
=> compact view: don't auto-scroll to the right on long filenames

libcaja-private/caja-undostack-manager.c
malloc may return NULL with memory allocation failure.
It will cause NULL pointer dereference crash.
=> Use g_malloc instead of malloc to be safe

libcaja-private/caja-icon-container.c
If we don't do this, we ignore any other double click event that happen
during the next 'gtk-double-click-time' interval after the first double
click.
taken from:
https://git.gnome.org/browse/nautilus/commit/?id=a8539a6
=> icon-container: reset the double click counter after a double click

src/file-manager/fm-properties-window.c
Notes and Image Properties tabs went missing after https://github.com/mate-desktop/caja/commit/451eef9b275ce006b270a3569d96e531e24dd15a
fixes https://github.com/mate-desktop/caja/issues/433
@infirit @flexiondotorg @NiceandGently
please test for any possible regressions
=> file properties dialog: bring back two missing tabs

libcaja-private/caja-file.c, libcaja-private/caja-undostack-manager.c
Fixes #361.
@infirit @flexiondotorg @NiceandGently
please test for any possible regressions :smile:
=> [1.10] don't crash on Ctrl-Z after deleting file when original path isn't stored in trash

libcaja-private/caja-autorun.c
This reduce the size to a normal level like with gtk2.
=> GTK3: reduce size of autorun-dialog

eel/eel-gtk-extensions.c, eel/eel-labeled-image.c, libcaja-private/caja-file-conflict-dialog.c, libcaja-private/caja-icon-container.c, libcaja-private/caja-mime-application-chooser.c, libcaja-private/caja-open-with-dialog.c, libcaja-private/caja-progress-info.c, src/caja-autorun-software.c, src/caja-connect-server-dialog.c, src/caja-image-properties-page.c, src/caja-location-bar.c, src/caja-notebook.c, src/caja-x-content-bar.c, src/file-manager/fm-directory-view.c, src/file-manager/fm-ditem-page.c, src/file-manager/fm-list-view.c, src/file-manager/fm-properties-window.c
@monsta 
@lukefromdc 
Please test.
Here a review is needed.
Most changes correct only deprecated gtk_misc_set_alignment for labels from pevious fix.
But i fixes also deprecated gtk_misc_{set/get}_padding in a few files.
Hope that i didn't break anything:)
=> GTK3: fix deprecated GtkMisc

libcaja-private/caja-module.c
My extension management code (GSoC2014) caused a regression that stops multiple Python extensions from loading correctly. This issue was reported as [issue 3](https://github.com/mate-desktop/python-caja/issues/22) on the python-caja tracker. This commit fixes the immediate problem.
=> fix loading multiple python extensions (regression since 1.9.3)

src/caja-desktop-window.c
Reset default size of desktop window to -1 in GTK 3.19/20 only. The combination of a non-resizable 
window with a default size is what causes the desktop to open wrong size.
based on https://github.com/GNOME/nautilus/commit/cf79068dc70c87e963e217e2e8ae149ee5ed1872
"desktop-window: avoid wrong size"
"gtk+ recently changed and unresizable windows now take into account
the default size set. We set the default size for normal resizable
windows in nautilus."
"However the desktop window is a no resizable window. What happens now
when setting a default size is that that size is used instead of the
widget request size, since window sizing now takes precedence over
widget sizing."
"To fix it, set the default size to -1 to override what the nautilus
window does by default, so we can avoid this …
=> GTK 3.20-fix wrong desktop size 

eel/eel-background.c, libcaja-private/caja-icon-container.c
@raveit65 @bl0ckeduser @alexandervdm @XRevan86
Hopefully this should fix all the font color issues for good. Please test it if you can. GTK+3 build shouldn't be affected by these changes due to ```#if```'s, so it should be enough to test GTK+2 build.
Please check whether **icon view** always has the right font color, and no regressions occur:
- desktop:
- desktop font color should be white with black shadow, no matter which background color, gradient, or a wallpaper is chosen (https://github.com/mate-desktop/caja/issues/105 shouldn't happen);
- Caja window:
- when no custom background is set and you switch between light and dark themes, font color should be black with light themes and white with dark themes (https://github.com/mate-desktop/caja/issues/81 shouldn't happen);
- when custom …
=> fix font color issues in GTK+2 build

src/caja-history-sidebar.c, src/caja-information-panel.c, src/caja-location-bar.c, src/caja-pathbar.c, src/caja-places-sidebar.c, src/caja-sidebar-title.c, src/caja-zoom-control.c
Port over all the remaining instances of GtkStyle I could find in Caja, keep caja-sidebar-title.c from fixes6 branch. Details below:
caja-sidebar-title.c Same file from https://github.com/lukefromdc/caja/tree/gtk3.21fixes6 GTK3: Ports update_title_font to GtkStyleContext and limit style_set function to calling update_title_font in GTK3 builds as latter function interferes with resizing fonts and does little else in GTK2.
caja-places-sidebar.c: Port caja_places_sidebar_style_set to GtkStyleContext in GTK3 builds
caja-pathbar.c: GtkStyleContext is already used to style the pathbar, so removed GtkStyle variables and unneeded caja_path_bar_style_set function
Note that this disables the most common call to caja_path_bar_check_icon_theme but icons update fine without it in GTK3. That being so, …
=> GTK3: port GtkStyle->GtkStyleContext

libcaja-private/caja-file-changes-queue.c, libcaja-private/caja-file-operations.c, libcaja-private/caja-icon-info.c, libcaja-private/caja-search-engine-simple.c, src/caja-spatial-window.c, src/caja-view-as-action.c
I know GMutex/GThread API is already fixed in caja, but this way it fixes a Wimplicit-function-declaration build warning in caja-search-engine-simple
@monsta @lukefromdc @flexiondotorg 
Please test and review.
=> deprecations and warnings

src/caja-pathbar.c
Beside from deprecation fixes and adding some style classes to the buttons, this is a very little design change.
I want to show the right slider(arrow) button every time.
This makes it possible to use a design what you know from nemo or nautilus with some themes, but without using the link button style class, using link buttons on pathbar is still broken since 3.16.
With using TOK or BlackMate themes it looks like this.
Menta or Submarine themes will obtain this pathbar design
I hope you agree with making the slider button always visible.
@monsta @lukefromdc @flexiondotorg 
please test
=> pathbar: improvements and deprecations

data/caja.css, libcaja-private/caja-icon-info.c
The button underallocation warnings came from pathbar sliders picking up padding from themes, then being forced to render to a smaller size in the code.
The GTK_ICON_LOOKUP_GENERIC_FALLBACK warnings came from the sidebar icons, this flag is now a source of errors. Unfortunately NULL does not work, so set GTK_ICON_LOOKUP_FORCE_SIZE, which does not create errors and ensures the icon size we actually want in the sidebar is used anyway.
Stops all but two of the warnings listed in https://github.com/mate-desktop/caja/issues/561
=> GTK3: stop warning spew from sidebar, pathbar

src/caja-pathbar.c
Fix gtk_widget_create_pango_layout: assertion 'GTK_IS_WIDGET (widget)' failed warning and those descending from it. This does NOT fix the  gtk_widget_set_size_request: assertion 'GTK_IS_WIDGET (widget)' failed, which occurs because recent GTK3 versions warn that button_data is not a GtkWidget but still succeed in setting the size. Since GTK 3.22 will be the LAST version of GTK3 this won't break until GTK4 if ever. Taking this out caused the pathbar buttons to jump on bold text so it had to be retained.
Also fix those "allocating size of GtkButton <xxxx> without calling gtk_widget get preferred width/height()" warnings from caja-pathbar's slider buttons
=> GTK3: fix pathbar pango and "preferred width/height"warnings

src/caja-pathbar.c, src/caja-window.c
Replace size request code with padding code borrowed from Nemo. For some reason gtk_widget_set_margin_start(or end) does not throw GTK warnings when called on GTK_WIDGET(button_date->label) while  gtk_widget_set_size_request does throw warnings. Neither generates a build warning.
=> GTK3: Fix last pathbar warning

src/caja-window.c
Apply https://github.com/itzexor/nemo/commit/2c60a3edaef10e9ef331740d55d3c45dd366c5db
window: remove custom get_preferred_width/height implementation
We already take care of the default size when we create the window, and these only break assumptions of the default GtkWindow's handlers.
in turn from
https://github.com/GNOME/nautilus/commit/da06dfc438e578405d616c48e8e3809d37c908bb
Nautilus commit is from Feb 17, 2014 prior to release of GTK 3.14. Could not build against GTK 3.14 over GTK 3.22 system due to mate-desktop errors but should work as Nautilus used it with 3.14. Test builds with GTK 3.16 and 3.22 worked fine, no issues with saved or command line geometry
=> GTK3: fix warnings cause by GtkGrid

cut-n-paste-code/libegg/eggsmclient.c, src/caja-application.c
Limit session management to non-root sessions within MATE to stop restart loops in root sessions and inablity to kill off Caja in non-mate sessions such as XFCE. Also remove the autostarted hold-in previously used to stop restart loops.
egg_sm_client_set_mode only works when called before the main loop starts, thus it cannot be used in GtkApplication startup functions or otherwise later in the program.
Note that this commit restores the Caja 3.16 and earlier restart loop in normal mate sessions if a user disables icons on the desktop, then sets exit_with_last_window. The combination is the default for root/not in mate sessions though, so without the ability to set "no restart" later than the start of the main loop, session management outside of MATE and in root sessions has to be …
=> GtkApplication: Disable session management when root/not in MATE

eel/eel-accessibility.c, eel/eel-accessibility.h, eel/eel-canvas.c, eel/eel-canvas.h, eel/eel-editable-label.c, eel/eel-labeled-image.c, libcaja-private/caja-icon-container.c, src/caja-zoom-control.c
Also disable eel accessibility code that is not needed.
Fixes https://github.com/mate-desktop/caja/issues/590
=> Fix accessible object inherritance when used with GTK >= 3.2

configure.ac, src/caja-application.h
Please use this as a reference. Building gtk3 without libunique does not work (edit: *with this patch*, for me). Possibly fixes #655.
=> Fix Gtk2 build issues with libunique and configure script error

configure.ac, libcaja-private/Makefile.am, libcaja-private/caja-file-operations.c, libcaja-private/caja-file-operations.h, libcaja-private/caja-global-preferences.h, libcaja-private/org.mate.caja.gschema.xml, src/Makefile.am, src/caja-application.c, src/caja-places-sidebar.c
Notify users when an external drive is still writing data on attempt to eject, and again when drive is safe to unmount. Notifications behave as they do in Nemo when ejecting/unmounting a flash drive. Tested with GTK 3.22 and a known slow flash drive.
This is in GtkApplication builds only, code is from Nemo. FIXME: build system does not limit libnotify dependency to GtkApplication builds and is rather improvised. Adding libnotify to CORE_MODULES via configure.ac did not work, and using Nemo's changes put -lnotify into CORE rather than ALL libs and that caused build failures on failure to link.
A better way to add libnotify to the linked libraries in "CORE" and to limit the dependency to GtkApplication builds during configuration would be nice, but this works as-is and …
=> GtkApplication: Notify when ejected volumes safe to unplug

src/file-manager/fm-icon-view.c
Apply Nautilus commit https://github.com/GNOME/nautilus/commit/0832acdb4371fc7de957303e220e899c8fdcdf5c
This causes vertical scroll wheel movement from the mouse to scroll the COMPACT view horizontally, the direction the scrollbars run in compact view. Previously there was no mousewheel scroll in compact view at all. NOT sure if we want to do this, Nemo does and has had some complaints by users wanting to turn it off. Should be possible to add a dconf key for that if people think that's necessary-or we could just leave this as-is.
=> Fix mousewheel scrolling in compact view

data/Makefile.am, data/caja-desktop.css, data/caja.css, src/caja-application.c
Fixes https://github.com/mate-desktop/caja/issues/688
Backport of https://github.com/mate-desktop/caja/commit/aa7af8673a3d894fc99a00d1a30ea57f44e3e1c5 to version 1.16
*Split caja.css. Much of it can load with GTK_STYLE_PROVIDER_PRIORITY_THEME to allow themes that support Caja to set their own style. CSS required for the desktop background to show and to keep the white text suitable for most backgrounds needs GTK_STYLE_PROVIDER_PRIORITY_APPLICATION so it is loaded separately from new file caja-desktop.css
*Move all css items that must not be overridden by themes (most of them are for the desktop) to caja-desktop.css and keep those that are only needed when themes do not set them at all in caja.css
=> Backport rename label fix to 1.16

libcaja-private/caja-icon-canvas-item.c
This makes the string exposed to ATK more sensible, instead of having unrelated words coupled together.
=> Add a separator when concatenating strings in icon text accessible

eel/eel-canvas.c, eel/eel-canvas.h, libcaja-private/caja-icon-canvas-item.c
Fix CajaIconCanvasItemAccessible inheritance to properly inherit from EelCanvasItemAccessible.  This fixes the ATK state machinery in CajaIconCanvasItemAccessible, and adds AtkComponent support which provides several useful features.
See also https://bugzilla.gnome.org/show_bug.cgi?id=677509 and https://github.com/mate-desktop/caja/issues/706.
Partly based off https://git.gnome.org/browse/nautilus/commit/?id=6c5baeb7626eda6629fc6642c9eb513ef8bc5c8e
---
Alternative simpler version of #711.
=> a11y: fix accessibility implementation for CajaIconCanvasItemAccessible (v2)

libcaja-private/caja-file-operations.c, libcaja-private/caja-global-preferences.h, libcaja-private/org.mate.caja.gschema.xml, src/caja-file-management-properties.c, src/caja-file-management-properties.ui
Add an option to show a confirmation dialog when moving files to the
trash, like there is for deleting files directly or emptying the trash.
Closes #632.
=> Add an option for asking confirmation before moving files to the trash

src/file-manager/fm-list-view.c
This is a backport from nautilus 5b09cedf434b53a975074b346d511335fc735cba
list-view: explicitly set cursor on file name cell renderer on rename
The file name column has two cell renderers, one for the icon and another for
the name string. Thus, gtk_tree_view_set_cursor() isn't enough to reliably
start editing the file name cell since it will try to edit whatever is the
currently focused cell in the column.
https://bugzilla.gnome.org/show_bug.cgi?id=656128
Fixes https://github.com/mate-desktop/caja/issues/741
=> Fix broken rename in list (issue #741)

eel/eel-canvas.c, libcaja-private/caja-icon-container.c
fixes https://github.com/mate-desktop/caja/issues/755
First time it's a bit hard to reproduce the issue, see this posts.
https://github.com/mate-desktop/caja/issues/755#issuecomment-292500277
https://github.com/mate-desktop/caja/issues/755#issuecomment-293630213
https://www.dropbox.com/s/8ftp9gois751892/caja-issue.ogv?dl=0
Note, i added a cosmetic back port of a nemo commit in another branch (dev-experimental), which reduce the width of the gap between grid of items and vertical right scrollbar.
Taken from https://github.com/linuxmint/nemo/pull/1257
But this dynamically grid change the look and feel of the icon-view and isn't really needed to fix the issue.
Please vote here if you like this behaviour or not.
=> fix scrolling and renaming in large folders

libcaja-private/caja-file.c
Finally found the relevant upstream commit. This should fix https://github.com/mate-desktop/caja/issues/410 in Mint (using ```caja-folder-color-switcher``` package) and Ubuntu (using ```folder-color-caja``` package). Maybe some other distros have it, but I don't know.
If you don't have folder-color available, please just check that I didn't break anything, in particular, in the list view and the bookmarks (that's where ```caja_file_get_gicon``` function is used, according to grep).
=> file: make caja_file_get_gicon return custom icons too

data/Makefile.am, data/caja-desktop-3.14.css, src/caja-application.c
In caja-desktop.css this line isn't compatible with GTK 3.14:
".caja-desktop:not(:selected):not(:active):not(.rubberband){"
It is needed for GTK 3.20/3.22 tough.
This PR checks the GTK version and loads the appropriate CSS.
This fixes desktop icons showing black text. That issue was
reproduced with Adwaita under LMDE with GTK 3.14.
=> CSS: Load a different caja-desktop.css with GTK 3.14

src/caja-pathbar.c
The pixel size difference between bold and normal fonts is not always even, so
it cannot be divided by 2. (Try not dividing by 2 and using padding only on the
right side).
And why use bold font at all? The buttons change when you click on them; that
should be enough. Or use CSS to change the font color to grey for inactive
buttons (use theme colors of course):
```
/* caja pathbar */
.caja-pathbar button label {
color: #cbcbcb;
/*font-weight: bold;*/
}
.caja-pathbar button:checked label {
color: #ffffff;
}
```
This will work as long as you don't set different font-weights for button label
and button:checked label.
=> Fix off-by-one error in caja-pathbar.c

src/file-manager/fm-icon-view.c
**Offered for testing.**
Should fix [Issue: 801](https://github.com/mate-desktop/caja/issues/801).
Was always scrolling to right when using sideways scrolling devices.
Now scrolls left or right with sideways scrolling devices and adjusts
vertical scrolling devices to scroll sideways.
I have completely rewritten the function `fm_icon_view_scroll_event()`. It used to fire a new event as a means to map vertical scroll events to horizontal ones. That made it difficult to find a solution without causing an infinite loop. Now it simply modifies the current event's values as needed.
It assumes that zero valued horizontal scroll events imply a vertical only scrolling device. This works well on my system changing the touchpad abilities between horizontal scrolling, vertical scrolling and both at …
=> fix vertical Compact View scrolling Issue 801

src/caja-application.c
Fix https://github.com/mate-desktop/caja/issues/807
A one-liner, tested with GTK 3.22.16 and works. 
Looks like this was left out of Nautilus 3.0, as I didn't find it in Nemo either
Both browsing inserted flash drives and auto-opening GNOME MPV to play a video DVD worked.  Responded properly to the preference settings. 
Note that on first run, setting preferences back to "never prompt or start programs on media insertion" while the DVD was still in and GNOME MPV still open generated a segfault (in libgtk), but this was not repeated on any subsequent runs when letting the media player autostart, then setting the preferences back to "never..." with the disk either playing or stopped.
=> Fix browsing/autorun media on insertion

cut-n-paste-code/libegg/eggtreemultidnd.c
Please test.
Its just the same i did here http://git.mate-desktop.org/engrampa/commit/?id=43ff5a233282bcd00ed36088c16cabe5255d10db
=> libegg: replace deprecated gtk_drag_begin

libcaja-private/caja-open-with-dialog.c
Fixes https://github.com/mate-desktop/caja/issues/828
=> Fix #828 "Open With" dialog "Open" button's text misaligned

src/caja-pathbar.c
Fixes https://github.com/mate-desktop/caja/issues/779
How to test:
- change into some directory 4-5 levels deep, so that pathbar would show enough buttons
- make the window narrow, so that not all pathbar buttons will be visible
- use mousewheel scroll on some buttons
This should do the same as the left/right arrow buttons on pathbar sides do.
=> pathbar: enable mousewheel scrolling like it was with GTK+2

src/file-manager/fm-list-view.c
With this PR, the behavior is as follows:
- column resizing works again
- if you don't resize a column manually before zooming, it will adapt its size on zoom in/out
- if you resize it manually before zooming, it will keep the size you've set (i.e. size won't change on zoom in/out)
- changing from list view to some other one and back will reset that behavior
I also checked the behavior in GTK+2 build of 1.16:
- column resizing works, but the minimum size of Name column is way too big, more than a half of the window
- if you don't resize a column manually before zooming, it will get bigger on zoom in, but doesn't get smaller on zoom out
- if you resize it manually before zooming, it will keep the size you've set (i.e. size won't change on zoom in/out)
- changing from list view to some …
=> list view: fix regression from #835

eel/eel-background.c
Fixes #606
with this PR the gssetings key `org / mate / background / picture-filename` only accepts an existing filename
=> Fix: high cpu while loading background image

libcaja-private/caja-icon-dnd.c
The call to gtk_render_frame() should be enough;
Now the .dnd style class setting from themes are used.
Fixes https://github.com/mate-desktop/mate-themes/issues/194
origin commit:
https://git.gnome.org/browse/nautilus/commit/?id=8d8979f
=> icon-dnd: remove hardcoded highlight frame

src/file-manager/fm-directory-view.c
Fixes https://github.com/mate-desktop/caja/issues/859
In the issue is suggested [ctrl+shift+o] to open new window
Currently [ctrl+shift+o] works to open in new tab, and it happens since years ago, so, I suppose some users prefer to keep it with no changes
I suggest the change in "open new window" to [ctrl+shift+w], it can be done faster, with one hand
=> open folder in new window: [ctrl] + [shift] + [w]

src/file-manager/fm-list-view.c
Fixes https://github.com/mate-desktop/caja/issues/698
=> Fix: wrong behavior with key "enter" while renaming files in list view

libcaja-private/caja-file-operations.c, src/caja-places-sidebar.c
Prevent "it is now safe to remove the drive" notification from being shown if unmounting fails or is cancelled by the user(e.g when the drive is busy). Also remove function in src/caja-places-sidebar.c for sending the notification as the same function in libcaja-private/caja-file-operations.c already sends it.
=> Fix eject notifications

src/caja-file-management-properties.c
passing argument 2 of ‘gtk_about_dialog_set_authors’ from incompatible pointer type
=> caja-file-management-properties.c: Fix build warning:

eel/eel-wrap-table.c, libcaja-private/caja-column-chooser.c, libcaja-private/caja-mime-application-chooser.c, libcaja-private/caja-open-with-dialog.c, src/caja-history-sidebar.c, src/caja-notes-viewer.c, src/caja-property-browser.c, src/caja-query-editor.c, src/file-manager/fm-desktop-icon-view.c, src/file-manager/fm-directory-view.c, src/file-manager/fm-tree-view.c
Make it consistent with behaviour for caja-places-sidebar.
You need to run caja as super user to see the scrollbars again.
=> ui: don't use overlay-scrollbars

eel/eel-string.c, src/caja-query-editor.h, src/caja-window-bookmarks.h
These files are sitting next to the files that include them, therefore include them with `""` instead of `<>`.
=> Include local files with "" instead of <>

eel/eel-wrap-table.c
Fix https://github.com/mate-desktop/caja/issues/506
Note that it still takes a few seconds for new content to show when switching between patterns, colors, and emblems but now they at least appear. Also it was necessary to use gtk_widget_queue_allocate and not gtk_widget_queue_resize to avoid massive amounts of  "Allocating size to<all widgets using eel_wrap_table> without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?" log spam.
=> fix backgrounds and emblems dialog content rendering

src/caja-bookmarks-window.ui
The expected: press [control + B] and see the same look like before
I edited the old file with Glade 3.20.2 to do the job, and I used **translatable="yes"** <- This is the correct way to work with _transifex_ later?
=> caja-bookmarks-window.ui: avoid deprecated GtkButton:use-stock

src/caja-file-management-properties.ui
avoid deprecated GtkImage:stock and GtkButton:use-stock
the expected: the same look like before
=> caja-file-management-properties.ui: avoid stock properties:

eel/eel-editable-label.c
avoid `gtk_image_menu_item_new_from_stock` and add icon to "Select All"
without the PR:
with the PR:
=> eel-editable-label.c: avoid gtk_image_menu_item_new_from_stock

eel/eel-stock-dialogs.c, libcaja-private/caja-mime-actions.c, libcaja-private/caja-program-choosing.c, src/caja-navigation-window-menus.c, src/caja-window-bookmarks.c, src/file-manager/fm-directory-view.c
This PR affects some dialogs, I have tested with these dialogs:
=> avoid eel_create_question_dialog with stock ids

eel/eel-editable-label.c, eel/eel-gtk-extensions.c, eel/eel-gtk-extensions.h, src/file-manager/fm-tree-view.c
gtk_image_menu_item_new_from_stock
gtk_image_menu_item_new_with_mnemonic
=> fm-tree-view.c: avoid deprecated GtkImageMenuItem

src/caja-emblem-sidebar.c
gtk_image_menu_item_new_with_label
gtk_image_menu_item_new_from_stock
=> caja-emblem-sidebar.c: avoid deprecated GtkImageMenuItem

src/caja-places-sidebar.c
gtk_image_menu_item_new_with_mnemonic
gtk_image_menu_item_new_with_label
=> caja-places-sidebar.c: avoid deprecated GtkImageMenuItem

libcaja-private/caja-bookmark.c, src/caja-navigation-action.c
gtk_image_menu_item_new_with_label
=> caja-bookmark: avoid deprecated GtkImageMenuItem

src/caja-navigation-window-menus.c
Fixes https://github.com/mate-desktop/caja/pull/965#issuecomment-377716724
=> caja-navigation-window-menus.c: drop unused variable

src/caja-navigation-window-pane.c
gtk_image_menu_item_new_with_mnemonic
=> caja-navigation-window-pane.c: avoid deprecated GtkImageMenuItem

src/caja-side-pane.c
gtk_image_menu_item_new_with_label
=> caja-side-pane.c: avoid deprecated GtkImageMenuItem

libcaja-private/caja-icon-canvas-item.c, libcaja-private/caja-icon-info.c, src/caja-pathbar.c
*caja-pathbar: fix warning,and in the process maybe fix occassional segfaults on opening a mounted device from the desktop
*caja-icon-info: Stop  gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed warning by handling NULL return from function finding the pixbuf
caja-icon-canvas-item-c: do not use g_object_unref where it does not work Stop the g_object_unref: assertion 'G_IS_OBJECT (object)' failed warnings on closing icon views
=> Fix warnings from HiDPI commits

src/file-manager/caja-icon-view-ui.xml, src/file-manager/fm-icon-view.c
This was introduced in commit b28445b3d2c42a7d2dbac97983d007e4ab58684d
but has never been added to some parts of the UI.
The GUI part was only implemented for the list view (but still selectable as default in the preferences for other views).
=> fm-icon-view: Show size on disk as sort criterion

src/caja-navigation-window-pane.c, src/caja-pathbar.c, src/caja-pathbar.h
Apply Nautilus commit
https://github.com/GNOME/nautilus/commit/e1ad3c05a6cd08c8cbf18ae53701dd742249d5fd#diff-f896071d07d34e87af94a18de95e4ea2
"pathbar: add a path-event signal"
and then apply most of
https://github.com/GNOME/nautilus/commit/875efc324f8e91f2d157c7532fe5570c1de421c7#diff-f896071d07d34e87af94a18de95e4ea2
pathbar: remove unused code
Which removes the function that was randomly segfaulting on creating certain navigation windows, usually on clicking a mounted volume from the desktop, probably by being called before the window was created. Replacement in button-event should never be called before the buttons exist
=> pathbar: fix random segfaults on opening mounts from Desktop

libcaja-private/caja-icon-canvas-item.c, libcaja-private/caja-icon-container.c
caja_icon_canvas_item_set_property was emitting accessible-name-change
signals whenever the PROP_EDITABLE_TEXT was being set for an icon. This
method is called by caja_icon_container_request_update_all when the icon
view is first loaded. Thus irrelevant events are being emitted (the name
of each icon didn't change, as far as the user is concerned). Furthermore,
this floods assistive technologies any time the user opens a folder with
a large number of files.
Moving the notification out of caja_icon_canvas_item_set_property and
into end_renaming_mode (where ICON_TEXT_CHANGED is also emitted) solves
the problem of floods of irrelevant notifications while still emitting
the signal when the name actually changes.
=> Emit accessible-name-change signal for icons only when icons are renamed

libcaja-private/caja-icon-container.c
Accessible children-changed events should not be emitted during the
initial load of the icon container. They should only be emitted when
a user-triggered action (creation of file, copying an item) causes
an item to be added.
By setting container->details->is_loading (which does not seem to
be used anywhere) and adding a call to finish_adding_new_icons when
all icons have been added, we can make the needed distinction and
emit the signal only when it makes sense to do so.
=> Eliminate accessible children-changed event flood during initial load

eel/eel-gtk-extensions.c, eel/eel-gtk-extensions.h, src/caja-information-panel.c, src/caja-places-sidebar.c, src/caja-zoom-control.c, src/file-manager/fm-directory-view.c
zoom-contol:
In favor of constant using of gtk_menu_popup_at_widget for mouse and keyboard events.
Now the popup is under the zoom-button if using mouse.
eel-gtk-extensions: 
open all context menus under pointer, same like before.
=> replace deprecated gtk_menu_popup function part 2

eel/eel-editable-label.c
I just deleted the related lines, it seems we don't need it
Do you see collateral effects with this PR?
=> eel-editable-label: avoid deprecated gtk_style_context_set_background

eel/eel-editable-label.c
drop "Input Methods"
I am not sure, we need it?
**EDIT**: with this PR:
=> editable-label: avoid deprecated 'gtk_im_multicontext_append_menuitems'

src/caja-desktop-window.c, src/caja-desktop-window.h
Screen readers need to distinguish between the desktop window and normal
windows, to be able to provide nicer speech synthesis.
This can be done by simply adding an "is-desktop" attribute to the
underlying AtkObject.
This is here done by introducing a thin caja_desktop_window_accessible_class
class which is based on GtkWindowAccessible and just appends the
attribute.
Closes: #999
=> desktop window: Add is-desktop AtkObject attribute

src/caja-sidebar-title.c
fixes
```
caja-sidebar-title.c:452:5: warning: 'state' may be used uninitialized in this function [-Wmaybe-uninitialized]
gtk_style_context_get (context, state, GTK_STYLE_PROPERTY_FONT, &title_font, NULL);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> Caja sidebar title warning

libcaja-private/caja-progress-info.c
gtk_status_icon_new_from_icon_name
gtk_status_icon_set_tooltip_text
gtk_status_icon_get_visible
gtk_status_icon_set_visible
I just removed the related code, someone can see differences in the behavior?
**EDIT:** PR modified, see the new title
=> caja-progress-info.c: avoid deprecated 'gtk_status_icon_get_visible' and show notifications

libcaja-private/caja-directory-background.c
The string returned by eel_bg_get_desktop_color() needs to be freed by
the caller, which wasn't happening before.
Commit b9cf3667 fixed the case where this function was being called
repeatedly, triggering this leak and causing it to rapidly fill system
memory.
=> [desktop-bg] Fix memory leak during background change events

libcaja-private/caja-directory.c, src/caja-pathbar.c
Stop button_data_file_changed: assertion 'path_bar->current_path != NULL' warnings and crashes. Note that these warnings do not appear with GTK 3.22, and the crashes occur only if GTK is built with --enable-debug=no. If GTK 3.23 is built with --enable-debug=minimal(as with release versions), these warnings still appear from the pathbar on toggling desktop_is_home_dir or rapidly opening many windows, but Caja does not crash:
```
(caja:13075): GLib-GObject-CRITICAL **: 22:31:36.471: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
** (caja:13075): CRITICAL **: 22:31:36.504: button_data_file_changed: assertion 'path_bar->current_path != NULL' failed
(caja:13075): GLib-GObject-CRITICAL **: 22:31:36.932: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
(caja:13075): …
```
=> GTK 3.23: fix warnings and crash from pathbar

libcaja-private/caja-desktop-directory.c
Prevent segfault on g_list_find in directory_ready_callback by catching the NULL case. This segfault can happen on rare occasions with GTK 3.23.0, I've had it several times in a week.
=> caja-desktop-directory: stop segfaults in directory_ready_callback

src/caja-window.c
Fixes https://github.com/mate-desktop/caja/issues/1024
=> caja-window: Fix: mouse doesn't work with [ctrl] + [.] or [ctrl] + [;]

libcaja-private/org.mate.caja.gschema.xml, src/caja-navigation-window.c
If true the gsettings key "ctrl-tab-switch-tabs" into "org.mate.caja.preferences"
Closes https://github.com/mate-desktop/caja/issues/768
We have the PR https://github.com/mate-desktop/caja/pull/825 since a lot time ago without changes,  so, I decide to open an alternative PR
=> add the ability to switch tabs using [ctrl+tab] and [ctrl+shift+tab]

libcaja-private/caja-file.c, libcaja-private/caja-icon-info.c, src/file-manager/fm-directory-view.c
Backport these two Nemo commits to Caja:
https://github.com/linuxmint/nemo/commit/61368e3fc33c0d662f45731d6bbb2a28fc5023ca
nemo-view.c: Decrease minimum update interval. 
https://github.com/linuxmint/nemo/commit/98843e26b48cd3526cacfe90cfa4ba201d1f3aee
nemo-icon-info: Optimize icon lookups by GIcon.
Each of these significantly sped up Nemo in test benchmarks (shown in the commit comments and copied into commit comments in this PR), and my own testing in Caja bears out the speed improvements.
Fixes https://github.com/mate-desktop/caja/issues/1060
=> Backport two Nemo commits that substantially speed up opening and loading icon views

docs/caja.1
The commit https://github.com/mate-desktop/caja/commit/9e5ea15d104720cfee752c193b77f8b03558c6b9 added a --force-desktop option, but not updated the manpage. Fix it.
=> Update caja manpage with info about "--force-desktop" option

src/caja-application.c
There are some redundant empty lines in caja-application.c. Remove it.
=> caja-application.c: Remove redundant empty lines

libcaja-extension/Makefile.am, libcaja-extension/caja-configurable.c, libcaja-extension/caja-configurable.h, src/caja-file-management-properties.c
This commit just creates a 'CajaConfigurable' interface for extensions to implement, so that things like open-terminal can have configuration UIs.
A particular use-case is open-terminal, which is rather configurable, but this configuration is all hidden, leading to the problem of hidden settings that can make the extension unusable in some cases.
This shouldn't affect any localizable strings, as it just makes existing UI call a function if available.
The reason I added a second signal handler to the extensions list for the separate button is because passing two buttons in various other ways seems simply more likely to cause memory leaks (that said, if there's a better solution, I'll modify the PR accordingly).
I tested this by adding the interface to an extension with a debug-print-stub …
=> Add 'Configurable' extension interface, enabling Configure Extension

libcaja-private/caja-file-utilities.c, libcaja-private/caja-file-utilities.h, libcaja-private/caja-monitor.c
Fix https://github.com/mate-desktop/caja/issues/1066 "Caja caches folders from usb drives/disk"
Nowadays, we rely on G_FILE_MONITOR_EVENT_UNMOUNTED to be emitted when a
mount disappears, since we already monitor the directory, in order to
switch the view to a different location.
Since non-native mounts very likely won't have file monitoring though,
we're not going to receive such events in that case, and fail to
redirect the view as a consequence.
This patch fixes it by listening to the mount-removed signal on
GVolumeMonitor when a monitor is requested for a non-native mount, and
emulating a file removal in that case.
Backport  Nautilus commit /gitlab.gnome.org/GNOME/nautilus/commit/3891241ba760c59d284b7579dbd340651c8d4d29
note that caja_get_mounted_mount_for_root had to be added, while …
=> monitor: watch for removal of non-native mounts on GVolumeMonitor

libcaja-private/caja-file.c, src/caja-connect-server-dialog.c, src/file-manager/fm-properties-window.c
This cleans up commits from #1058 so that they preserve the log history
May fix the following issus (according to the original PR, yet to be tested)
* #1019 
* #954 
* #421
=> Backport permission fixes

libcaja-private/caja-monitor.c
Don't treat remote filesystems differently when unmounting, so that bookmarks can remount them if they are available and so caja does not crash.
An alternative to 
https://github.com/mate-desktop/caja/pull/1075
and to
https://github.com/mate-desktop/caja/pull/1074
=> Simpler fix for crash on umounting remote network shares, keeps any bookmarks from them valid

libegg/eggsmclient.c, src/caja-application.c, src/caja-main.c
The environment variable XDG_SESSION_DESKTOP and DESKTOP_SESSION in
running_in_mate are compared using g_strcmp0. Actually the environment
variable in MATE DE is "mate"(lower case). Using g_ascii_strcasecmp
instead of g_strcmp0 to fix it.
The XDG_SESSION_DESKTOP and DESKTOP_SESSION are set here:
https://github.com/CanonicalLtd/lightdm/blob/7241fd81c0dfcbe354f2c9bc4ace04088de5d860/src/seat.c#L979
export:
[root@localhost]# export |grep XDG_SESSION_DESKTOP
declare -x XDG_SESSION_DESKTOP="mate"
[root@localhost]# export |grep DESKTOP_SESSION
declare -x DESKTOP_SESSION="mate"
=> Fix case-insensitive in running_in_mate

src/caja-places-sidebar.c
Fix https://github.com/mate-desktop/caja/issues/1046
drive_stop_cb should never have used g_drive_poll_for_media_finish which is for
ejectable media in a fixed drive (e.g CD drive) and not for stopping a removable drive
See
https://developer.gnome.org/gio/stable/GDrive.html
https://developer.gnome.org/gio/stable/GDrive.html#g-drive-stop-finish
=> Fix segfault on stopping USB hard drives

src/file-manager/fm-directory-view.c
This reverts commit 021ff2ac062f1cfd52726c78e9a3956405001c6e.
Fixes https://github.com/mate-desktop/caja/issues/1101
=> Fix weird look in icon view

eel/eel-background.c, eel/eel-background.h, eel/eel-image-table.c, eel/eel-image-table.h, eel/eel-labeled-image.c, eel/eel-labeled-image.h, eel/eel-wrap-table.c, eel/eel-wrap-table.h, libegg/eggsmclient.c
With minimal changes to avoid deprecated g_type_class_add_private.
=> Avoid deprecated g_type_class_add_private

src/caja-application.c
Fix crash on starting with env DESKTOP_AUTOSTART_ID=ANY_CHARS caja
=> caja-application: Check for smclient before trying to load session

configure.ac
Add check for PKG_CONFIG being set.
Author: @sunweaver 
not sure how to test this PR, I just open this with the debian patch:
https://salsa.debian.org/debian-mate-team/caja/blob/debian/1.20.3-1/debian/patches/1001_use-correct-macros-to-cross-build.patch
=> configure.ac: Add check for PKG_CONFIG being set

libcaja-private/caja-query.c, libcaja-private/caja-search-engine-simple.c, src/caja-query-editor.c
Remove unused variables, avoid uninitialized variable warnings, and indent code.
=> Fix compile warning

.travis.yml
Because make distcheck has been fixed, the return value is directly detected.
=> Remove the distcheck return value override

libcaja-private/caja-file-operations.c, src/caja-sidebar-title.c
to avoid warnings with Clang Analyzer
```
caja-file-operations.c:6551:3: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
strcpy (new_contents, TRUSTED_SHEBANG);
^~~~~~
```
```
caja-sidebar-title.c:436:5: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
strcpy (tempfont, font);
^~~~~~
```
=> [Security] Use 'g_strlcpy' instead of 'strcpy'

eel/eel-string.c
to avoid warnings with Clang Analyzer
```
eel-string.c:249:5: warning: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119
strcat (truncated, delimter);
^~~~~~
eel-string.c:250:5: warning: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119
strcat (truncated, g_utf8_offset_to_pointer  (string, length - num_right_chars));
^~~~~~
```
=> [Security] eel-string: Use 'g_strlcat' instead of 'strcat'

libcaja-private/caja-tree-view-drag-dest.c
```
caja-tree-view-drag-dest.c:1032:19: warning: Potential leak of memory pointed to by 'filename'
child = g_file_get_child (base, filename);
~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> caja-tree-view-drag-dest: Fix memory leak

src/file-manager/fm-directory-view.c
```
fm-directory-view.c:5404:2: warning: Use of memory after it is freed
caja_debug_log (FALSE, CAJA_DEBUG_LOG_DOMAIN_USER,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> fm-directory-view: Fix use of memory after it is freed

src/caja-information-panel.c
```
caja-information-panel.c:954:35: warning: Use of memory after it is freed
temp_button = gtk_button_new_with_label (button_name);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> caja-information-panel: Fix use of memory after it is freed

src/file-manager/fm-tree-model.c
```
fm-tree-model.c:784:9: warning: Use of memory after it is freed
destroy_node_without_reporting (model, parent->first_child);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> fm-tree-model: Fix use of memory after it is freed

libcaja-private/caja-icon-container.c
```
caja-icon-container.c:7952:5: warning: Use of memory after it is freed
g_signal_emit (container, signals[ICON_REMOVED], 0, icon);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> caja-icon-container: Fix use of memory after it is freed

libcaja-private/caja-file.c
```
caja-file.c:8326:3: warning: Use of memory after it is freed
caja_file_call_when_ready (file,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> caja-file: Fix use of memory after it is freed

eel/eel-gdk-pixbuf-extensions.c
```
eel-gdk-pixbuf-extensions.c:403:29: warning: Division by zero
*dest++ = r / n_pixels;
~~^~~~~~~~~~
```
=> eel-gdk-pixbuf-extensions: Fix division by zero

src/caja-window.c
```
caja-window.c:554:34: warning: The left operand of '<' is a garbage value
MIN (default_width,
^    ~~~~~~~~~~~~~
```
=> caja-window: Fix garbage value

eel/eel-canvas.c
```
eel-canvas.c:3426:9: warning: Undefined or garbage value returned to caller
return item;
^~~~~~~~~~~
```
=> eel-canvas: Fix warning: Undefined or garbage value returned to caller

eel/eel-image-table.c, eel/eel-labeled-image.c, libcaja-private/caja-file-conflict-dialog.c, libcaja-private/caja-icon-canvas-item.c, libcaja-private/caja-keep-last-vertical-box.c, libcaja-private/caja-program-choosing.c, libcaja-private/caja-progress-info.c, src/caja-application.c, src/caja-connect-server-dialog-nonmain.c, src/caja-connect-server-dialog.c, src/caja-emblem-sidebar.c, src/caja-places-sidebar.c, src/caja-property-browser.c, src/caja-side-pane.c, src/caja-spatial-window.c, src/file-manager/fm-icon-view.c
This PR fixes the build warnings:
```
eel-image-table.c:102:20: warning: variable 'image_table' set but not used [-Wunused-but-set-variable]
eel-labeled-image.c:366:16: warning: variable 'window' set but not used [-Wunused-but-set-variable]
caja-file-conflict-dialog.c:565:14: warning: variable 'source_is_dir' set but not used [-Wunused-but-set-variable]
caja-icon-canvas-item.c:1700:24: warning: variable 'container' set but not used [-Wunused-but-set-variable]
caja-keep-last-vertical-box.c:92:13: warning: variable 'box' set but not used [-Wunused-but-set-variable]
caja-progress-info.c:466:12: warning: variable 'mypos' set but not used [-Wunused-but-set-variable]
caja-program-choosing.c:212:16: warning: variable 'total' set but not used [-Wunused-but-set-variable]
fm-icon-view.c:549:17: …
```
=> avoid variables set but not used

eel/eel-glib-extensions.c, eel/eel-glib-extensions.h, libcaja-private/caja-file.c, libcaja-private/caja-mime-actions.c, libcaja-private/caja-query.c
GNOME/nautilus@61e2aff
Replace eel_g_str_list_copy(Glist *list)
with g_list_copy_deep (list, (GCopyFunc) g_strdup, NULL)
=> eel: remove g_str_list_copy

configure.ac
"test ... ==" isn't a portable expression, change to POSIX "=".
=> configure.ac: fix portability issue with test

libcaja-private/caja-file-operations.c
avoid false positive Clang static analyzer warning:
```
caja-file-operations.c:958:11: warning: Cast a region whose size is not a multiple of the destination type size
common = g_malloc0 (job_size);
^~~~~~~~~~~~~~~~~~~~
```
=> caja-file-operations: add comment with false positive warning

libcaja-private/caja-file.c
```
caja-file.c:4858:9: warning: true and false branches are identical
} else if (file_date_age < 7) {
^
```
=> caja-file: Fix: true and false branches are identical

eel/eel-editable-label.c
```
eel-editable-label.c:2624:9: warning: 2nd function call argument is an uninitialized value
if (pango_layout_line_x_to_index (line,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> eel-editable-label: call argument with initialized value

libcaja-private/caja-autorun.c
```
caja-autorun.c:139:5: warning: Null pointer passed as an argument to a 'nonnull' parameter
memcpy (r, v, len * sizeof (char *));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> caja-autorun: avoid NULL in 'memcpy'

src/caja-sidebar-title.c
```
caja-sidebar-title.c:233:49: warning: Dereference of null pointer (loaded from variable 'color')
sidebar_title->details->label_colors[idx] = *color;
^~~~~~
```
with git master:
that line seems to be wrong, and it was fixed by this PR
=> caja-sidebar-title: avoid 'NULL' inside 'setup_gc_with_fg'

libcaja-private/caja-progress-info.c
```
caja-progress-info.c:626:17: warning: 1st function call argument is an uninitialized value
g_notification_set_body (notification, _("Process completed"));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> caja-progress-info: make sure argument is initialized

eel/eel-string.c
Fixes Clang static analyzer warnings:
```
eel-string.c:325:9: warning: Null pointer passed as an argument to a 'nonnull' parameter
memcpy (result_position, replacement, replacement_length);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
eel-string.c:319:13: warning: Memory copy function overflows destination buffer
memcpy (result_position, p, remaining_length);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> eel-string: Fix Clang static analyzer warnings

libcaja-private/caja-open-with-dialog.c
```
caja-open-with-dialog.c:252:100: warning: Access to field 'message' results in a dereference of a null pointer (loaded from variable 'error')
message = g_strdup_printf (_("Could not add application to the application database: %s"), error->message);
^~~~~~~~~~~~~~
```
=> caja-open-with-dialog: make sure there is error before showing it

libcaja-private/caja-file-operations.c
Fixes Clang static analyzer warnings:
```
caja-file-operations.c:2165:7: warning: Access to field 'code' results in a dereference of a null pointer (loaded from variable 'error')
if (error->code != G_IO_ERROR_FAILED_HANDLED) {
^~~~~~~~~~~
caja-file-operations.c:5448:14: warning: Access to field 'message' results in a dereference of a null pointer (loaded from variable 'error')
details = error->message;
^~~~~~~~~~~~~~
```
=> caja-file-operations: make sure 'error' isn't NULL

src/file-manager/fm-desktop-icon-view.c
Fixes Clang static analyzer warnings:
```
fm-desktop-icon-view.c:331:33: warning: 1st function call argument is an uninitialized value
if (pointer == NULL && (gdk_device_get_source (cur) == GDK_SOURCE_MOUSE)) {
^~~~~~~~~~~~~~~~~~~~~~~~~~~
fm-desktop-icon-view.c:335:34: warning: 1st function call argument is an uninitialized value
if (keyboard == NULL && (gdk_device_get_source (cur) == GDK_SOURCE_KEYBOARD)) {
^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> fm-desktop-icon-view: remove dead code

src/caja-application.c
```
caja-application.c:2221:25: warning: Array access (from variable 'files') results in a null pointer dereference
g_object_unref (files[idx]);
^~~~~~~~~~
```
=> caja-application: avoid NULL inside 'g_object_unref'

src/file-manager/fm-directory-view.c, src/file-manager/fm-icon-view.c
Pass "NULL" for event which is passed ultimately to gtk_menu_popup_at_pointer as an invalid event was being passed when the menu key was used to open the icon views context menu
=> Fix  #1198 "Context menu with menu key broken"

libcaja-private/caja-icon-canvas-item.c
Fixes `cppcheck` warning:
`[libcaja-private/caja-icon-canvas-item.c:517]: (error) Uninitialized variable: scale`
=> caja-icon-canvas-item: initialize variable 'scale'

src/caja-application.c
Due to changes somewhere else windows called with --geometry must now be opened before splitedOptions is freed or the geometry passed to later functions gets corrrupted
Note that setting a width smaller than 654 px will generate GTK warnings (negative content width and similar) but will still mostly work.
=> Fix invocation with --geometry from the command line

libcaja-private/caja-file.c
Fixes `cppcheck` warnings:
```
[libcaja-private/caja-file.c:288]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
[libcaja-private/caja-file.c:334]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
[libcaja-private/caja-file.c:386]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
[libcaja-private/caja-file.c:3789]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
```
=> caja-file: avoid shifting signed 32-bit value by 31 bits

libcaja-private/caja-icon-canvas-item.c
Fixes `cppcheck` warning:
`[libcaja-private/caja-icon-canvas-item.c:850]: (error) Uninitialized variable: real_text_height`
=> caja-icon-canvas-item: avoid 'cppcheck' warning

eel/eel-editable-label.c
Fixes 'flawfinder' warning:
`(buffer) memcpy: Does not check for buffer overflows when copying to destination (CWE-120). Make sure destination can always hold the source data.`
http://cwe.mitre.org/data/definitions/120.html
The expected with this PR: the same behavior renaming folders and files.
=> eel-editable-label: Use 'memmove' instead of 'memcpy'

eel/eel-string.c
Fixes `cppcheck` warnings:
```
[eel-string.c:681]: (error) va_list 'va' used before va_start() was called.
[eel-string.c:682]: (error) va_list 'va' used before va_start() was called.
[eel-string.c:683]: (error) va_list 'va' used before va_start() was called.
[eel-string.c:684]: (error) va_list 'va' used before va_start() was called.
[eel-string.c:697]: (error) va_list 'va' used before va_start() was called.
[eel-string.c:698]: (error) va_list 'va' used before va_start() was called.
[eel-string.c:699]: (error) va_list 'va' used before va_start() was called.
[eel-string.c:700]: (error) va_list 'va' used before va_start() was called.
[eel-string.c:709]: (error) va_list 'va' used before va_start() was called.
[eel-string.c:710]: (error) va_list 'va' used before va_start() was called. …
```
=> eel-string: Use 'va_copy' instead of 'G_VA_COPY'

libcaja-private/caja-file-utilities.c, libegg/eggsmclient-xsmp.c, src/caja-property-browser.c
Fix cast from non-struct type to struct type
Fixes Clang static analyzer warnings:
```
eggsmclient-xsmp.c:1156:18: warning: Casting a non-structure type to a structure type and accessing a field can lead to memory access errors or data corruption
prop->vals = (SmPropValue *)vals->data;
^~~~~~~~~~~~~~~~~~~~~~~~~
eggsmclient-xsmp.c:1189:18: warning: Casting a non-structure type to a structure type and accessing a field can lead to memory access errors or data corruption
prop->vals = (SmPropValue *)vals->data;
^~~~~~~~~~~~~~~~~~~~~~~~~
caja-file-utilities.c:283:12: warning: Casting a non-structure type to a structure type and accessing a field can lead to memory access errors or data corruption
return (XdgDirEntry *)g_array_free (array, FALSE);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```
=> Fix cast from non-struct type to struct type

src/caja-location-dialog.c
Fixes 'cppcheck' warnings:
```
[src/caja-location-dialog.c:229] -> [src/caja-location-dialog.c:237]: (warning) Either the condition 'window' is redundant or there is possible null pointer dereference: window.
[src/caja-location-dialog.c:224]: (style) The scope of the variable 'formatted_location' can be reduced.
```
```
caja-location-dialog.c:237:12: warning: Access to field 'details' results in a dereference of a null pointer (loaded from variable 'window')
slot = window->details->active_pane->active_slot;
^~~~~~~~~~~~~~~
```
=> caja-location-dialog: Fix 'cppcheck' and 'clang' warnings

eel/eel-background.c, eel/eel-canvas-rect-ellipse.c, eel/eel-canvas.c, eel/eel-debug.c, eel/eel-editable-label.c, eel/eel-gdk-pixbuf-extensions.c, eel/eel-glib-extensions.c, eel/eel-graphic-effects.c, eel/eel-gtk-extensions.c, eel/eel-labeled-image.c, eel/eel-mate-extensions.c, eel/eel-stock-dialogs.c, eel/eel-string.c, eel/eel-vfs-extensions.c, eel/eel-wrap-table.c
Fixes 'cppcheck' warnings:
```
[eel/eel-background.c:163]: (style) The scope of the variable 'intensity' can be reduced.
[eel/eel-background.c:163]: (style) The scope of the variable 'saturation' can be reduced.
[eel/eel-background.c:196]: (style) The scope of the variable 'end_color' can be reduced.
[eel/eel-canvas-rect-ellipse.c:600]: (style) The scope of the variable 'tmp' can be reduced.
[eel/eel-canvas-rect-ellipse.c:705]: (style) The scope of the variable 'width_pixels' can be reduced.
[eel/eel-canvas-rect-ellipse.c:706]: (style) The scope of the variable 'width_lt' can be reduced.
[eel/eel-canvas-rect-ellipse.c:706]: (style) The scope of the variable 'width_rb' can be reduced.
[eel/eel-canvas.c:1420]: (style) The scope of the variable 'child' can be reduced. …
```
=> eel: reduce the scope of some variables

configure.ac, eel/eel-glib-extensions.c, eel/eel-glib-extensions.h, eel/eel-stock-dialogs.c, libcaja-private/caja-dnd.c, libcaja-private/caja-file.c, libcaja-private/caja-icon-container.c, libcaja-private/caja-icon-dnd.c, src/caja-file-management-properties.c, src/file-manager/fm-directory-view.c, src/file-manager/fm-list-view.c
Do not need to extend glib library, since it now incorporates these functions.
Extended date format modifiers are available on [glib v2.56](https://bugzilla.gnome.org/show_bug.cgi?id=749206).
eel-glib-extensions.h/c:
```C
GDate * eel_g_date_new_tm (struct tm *time_pieces);
char * eel_strdup_strftime (const char *format, struct tm *time_pieces);
gint64 eel_get_system_time (void);
```
Do not need to test the extensions in `eel_self_check_glib_extensions (void)`.
eel-glib-extensions.c:
```C
static void check_tm_to_g_date (time_t time)
static char * test_strftime (...)
```
Do not need to check if strftime implements extended date format modifiers on the system (available on [glibc v2.27](https://sourceware.org/bugzilla/show_bug.cgi?id=10871)).
configure.ac
=> eel: remove date & time functions

libegg/eggdesktopfile.c, libegg/eggsmclient-xsmp.c, libegg/eggtreemultidnd.c
Fixes 'cppcheck' warnings:
```
[libegg/eggdesktopfile.c:483]: (style) The scope of the variable 'try_exec' can be reduced.
[libegg/eggdesktopfile.c:483]: (style) The scope of the variable 'found_program' can be reduced.
[libegg/eggdesktopfile.c:484]: (style) The scope of the variable 'only_show_in' can be reduced.
[libegg/eggdesktopfile.c:484]: (style) The scope of the variable 'not_show_in' can be reduced.
[libegg/eggdesktopfile.c:486]: (style) The scope of the variable 'i' can be reduced.
[libegg/eggdesktopfile.c:608]: (style) The scope of the variable 'p' can be reduced.
[libegg/eggsmclient-xsmp.c:227]: (style) The scope of the variable 'cmdline' can be reduced.
[libegg/eggsmclient-xsmp.c:773]: (style) The scope of the variable 'fd' can be reduced.
[libegg/eggsmclient-xsmp.c:808]: …
```
=> libegg: reduce the scope of some variables

eel/eel-canvas.c
Fixes `cppcheck` warning:
`[eel/eel-canvas.c:3261] -> [eel/eel-canvas.c:3297]: (style) Local variable allocation shadows outer variable`
=> eel-canvas: cppcheck: Local variable 'allocation' shadows outer variable

libcaja-private/caja-open-with-dialog.c
Fixes `cppcheck` warning:
`[libcaja-private/caja-open-with-dialog.c:265]: (style) Redundant condition: !dialog->details->add_mode. 'A || (!A && B)' is equivalent to 'A || B'`
=> caja-open-with-dialog: cppcheck: Redundant condition

libcaja-private/caja-clipboard.c, libcaja-private/caja-ui-utilities.c, src/file-manager/fm-desktop-icon-view.c, src/file-manager/fm-directory-view.c
This suppress noise from Gtk_Action and GtkUIManager in build logs and make them readable.
Gtk_Action and GtkUIManager can't be replace without loosing our icons.
So this have to be stay until we switch to GTK4, if we really do that.
Please review.
=> Silent gtk action

libcaja-private/caja-clipboard.c, libcaja-private/caja-ui-utilities.c, src/file-manager/fm-desktop-icon-view.c, src/file-manager/fm-directory-view.c
https://caja.mate-desktop.dev
cppcheck warnings:
master branch: 397
this PR: 350
seems `G_GNUC_BEGIN_IGNORE_DEPRECATIONS` and `G_GNUC_END_IGNORE_DEPRECATIONS` need semicolon
gtk code already have semicolon, for reference, see: https://github.com/GNOME/gtk/blob/gtk-3-22/gtk/deprecated/gtkaction.c#L226
=> Fix cppcheck warnings appeared since the silence of deprecated gtkaction warnings

src/file-manager/fm-directory-view.c
Fixes `cppcheck` warnings:
```
[src/file-manager/fm-directory-view.c:1007]: (style) Statements following return, break, continue, goto or throw will never be executed.
[src/file-manager/fm-directory-view.c:1080]: (style) Statements following return, break, continue, goto or throw will never be executed.
```
=> fm-directory-view: change G_GNUC_END_IGNORE_DEPRECATIONS place

.travis.yml
The warnings of deprecated GtkAction are silenced by the PR https://github.com/mate-desktop/caja/pull/1221
I don't agree, and I did this PR to show all the warnings in debian build with travis.
=> Travis CI: debian build: show all the warnings of deprecated functions

data/caja-desktop.css, libcaja-private/caja-icon-canvas-item.c
Draw the frame under the items label even when not selected and not in prelight state, so that it is possible to theme it in the other states. However we still don't draw it when editing, because there is the editing widget frame already and drawing the label's one might slightly overflow the editing widget's borders and lead to slightly ugly results.
Being able to draw a background is especially useful for accessibility purposes (e.g. a high contrast theme would typically make sure there is a background with enough contrast), but might be useful to all as desktop backgrounds are often not uniform at all.
By default this is drawn transparent on the non-selected and non-prelight states (no change in default appearance then), but allows the user to customize it with a background if need be. …
=> desktop: Always draw the items label frame

libcaja-private/caja-icon-info.c
In caja-icon-info.c use GTK_ICON_LOOKUP_FORCE_SIZE flag to ensure that icons actually scale when window-scaling-factor is set to 2 or more. Tested at window-scaling-factor=1 and window-scaling-factor=2
=> hidpi: ensure all icons are properly scaled

src/file-manager/fm-desktop-icon-view.c
Taken from https://github.com/linuxmint/nemo/commit/89090ac192638d75359876d917b6d3ce106196af. It's a fix for a random crash which can be probably triggered by changing the desktop font while the desktop icon view is being deleted... I only saw a report about it on Launchpad ([here](https://bugs.launchpad.net/bugs/1598262)). In other words, if nobody can reproduce the crash, just check that things work as before :slightly_smiling_face:
=> desktop icon view: disconnect callback from correct GSettings instance

data/caja-desktop.css
18e4fbd005bd561e4a12ed388d4d9a8c93f0b15b started always drawing the frame on canvas items for the desktop's sake, but it also impacts other icon views.  This is good in theory, but conflicts with some themes that used to work fine and now display an unwanted background because of generic rules matching these elements.
Unfortunately there don't seem to be another solution than providing overrides for this yet, so do that, as anyway before recently the background wasn't drawn at all even if specified.
Spotted in https://github.com/mate-desktop/caja/pull/1240#issuecomment-507039580
=> Restore transparent background on icon view labels

libcaja-private/caja-file-conflict-dialog.c
Hardcode scale factor to 1 in  caja_file_get_icon_pixbuf functions in caja-file-conflict as these icons are already getting scaled elsewhere. Otherwise they get scaled twice and the whole dialog is ballooned oversize on hidpi
*Based on similar change made in Nautilus as a small part of fd01842f996b7d07baf2aafb0f68308fc5ed2055 "file-conflict-dialog: separate file logic from UI management " which was a more general refactoring of the file conflict dialog and split out the frontend and backend code.
=> file-conflict-dialog: don't scale icons twice on hidpi monitors

libcaja-private/caja-file-conflict-dialog.c, libcaja-private/caja-file.c, libcaja-private/caja-file.h
This reverts the changes in #1253 and instead renders icons using `cairo_surface_t` vectors, rather than `GdkPixbuf`. The result is the correct size, correct scale icon shown in higher quality.
Before:
After:
=> Render file-conflict icons as cairo_surface vectors

data/Makefile.am, data/a11y-caja-desktop-base.css, data/caja-desktop-ContrastHigh.css, data/caja-desktop-ContrastHighInverse.css, data/caja-desktop-HighContrast.css, data/caja-desktop-HighContrastInverse.css, src/caja-application.c
This allows to have a theme file to better fit desktop theming to a specific theme.  This is designed for themes with specific semantics, like High Contrast ones.
Support for HighContrast themes (both of the ones provided by GTK3, plus both current MATE's and an older of MATE's) is included, and can be used to test the feature: enable one of the High Contrast themes, and see the desktop items labels get drawn on plain background for optimal readability.
Adding support for a new theme is a simple matter of adding the rules in a file named `$caja_datadir/caja-desktop-$THEME.css`, it'll get automatically loaded when that theme `$THEME` is in use.
=> Add support for theme-specific desktop CSS overrides

eel/eel-gtk-extensions.c, eel/eel-gtk-extensions.h, libcaja-private/caja-file.c, libcaja-private/caja-file.h, src/caja-file-management-properties.c, src/caja-file-management-properties.ui, src/caja-sidebar-title.c, src/caja-spatial-window.c, src/file-manager/fm-empty-view.c
This updates a few more places where GdkPixbuf icons were rendered to using cairo_surface icons.
This one is hard to notice, but under high magnification the icon border looks sharper
Before:
After:
This one had larger than usual icons. Let me know if you want the surface icons to be large as well, but I think they look a bit out of place.
Before:
After:
Before:
After:
=> Render icons as cairo surfaces

src/file-manager/fm-desktop-icon-view.c, src/file-manager/fm-directory-view.c, src/file-manager/fm-ditem-page.c, src/file-manager/fm-icon-container.c, src/file-manager/fm-icon-view.c, src/file-manager/fm-list-model.c, src/file-manager/fm-list-view.c, src/file-manager/fm-properties-window.c, src/file-manager/fm-tree-model.c, src/file-manager/fm-tree-view.c
Fixes all the `cppcheck` scope variables warnings into the `src / file-manager` folder
=> src / file-manager: reduce the scope of some variables

src/file-manager/fm-empty-view.c
Fix build error when run `./configure --enable-empty-view`:
```
fm-empty-view.c: In function 'fm_empty_view_add_file':
fm-empty-view.c:67:12: error: too few arguments to function 'caja_file_get_icon_surface'
67 |     icon = caja_file_get_icon_surface (file, caja_get_icon_size_for_zoom_level (CAJA_ZOOM_LEVEL_STANDARD), TRUE, 0);
|            ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from fm-directory-view.h:37,
from fm-empty-view.h:28,
from fm-empty-view.c:36:
../../libcaja-private/caja-file.h:469:18: note: declared here
469 | cairo_surface_t *caja_file_get_icon_surface (CajaFile         *file,
|                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> fix build error about fm-empty-view

eel/eel-gtk-extensions.c, eel/eel-gtk-extensions.h, libcaja-private/caja-file.c, libcaja-private/caja-file.h, src/caja-file-management-properties.c, src/caja-file-management-properties.ui, src/caja-sidebar-title.c, src/caja-spatial-window.c, src/file-manager/fm-empty-view.c
Just a port of https://github.com/mate-desktop/caja/pull/1258 to 1.22 branch. Had to do some manual work due to conflicts, so please check I didn't mess up somewhere.
=> Render icons as cairo surfaces, backport to 1.22

libcaja-private/caja-file-operations.c
The timestamps are reset to the current time, even if the source &
target folders support these GFileInfo attributes.
Closes #1226
=> Copy file and keep timestamps of original file including remotes

data/Makefile.am
Example for Catalan (ca):
```shell
$ make clean
$ tx pull -l=ca -f
$ ./autogen.sh --prefix=/usr
$ make -C data caja.desktop
$ diff ../caja-master/data/caja.desktop data/caja.desktop
...
< Icon[ca]=system-file-manager
...
```
=> Don't export translation for Icon keyword in desktop files

src/caja-window-slot.c
=> caja-window-slot: "folder-saved-search" icon instead "text-x-generic"

libcaja-private/caja-icon-canvas-item.c
fixes https://github.com/mate-desktop/caja/issues/1284
Pango 1.44 got the ability to automatically hyphenate on line breaks,
which is on by default, but can be set off by a new attribute.
As a result, we now hyphenate filenames, which is confusing, because
a filename may already include hyphens.
To restore the previous behavior, let's not insert hyphens when
breaking filenames in multiple lines.
Inspired by https://gitlab.gnome.org/GNOME/nautilus/commit/9738d85
Please test.
=> canvas-item: Don't hyphenate filenames

libcaja-private/caja-file.c
'!A || (A && B)' is equivalent to '!A || B'
=> libcaja-private/caja-file: redundant condition

configure.ac, src/file-manager/fm-properties-window.c
don't use mate_desktop_thumbnail_scale_down_pixbuf().
gdk-pixbuf doesn't have the same bugs when shrinking images by large
factors.
Please review.
=> fm-properties: Remove use of mate-desktop-thumbnail helper

eel/eel-background.c, libcaja-private/caja-global-preferences.c, libcaja-private/caja-global-preferences.h
```
/usr/bin/ld: caja-bookmarks-window.o:/home/robert/caja/src/../libcaja-private/caja-global-preferences.h:215: multiple definition of `caja_preferences'; caja-application.o:/home/robert/caja/src/../libcaja-private/caja-global-preferences.h:215: first defined here
/usr/bin/ld: caja-bookmarks-window.o:/home/robert/caja/src/../libcaja-private/caja-global-preferences.h:226: multiple definition of `mate_lockdown_preferences'; caja-application.o:/home/robert/caja/src/../libcaja-private/caja-global-preferences.h:226: first defined here
/usr/bin/ld: caja-bookmarks-window.o:/home/robert/caja/src/../libcaja-private/caja-global-preferences.h:225: multiple definition of `mate_background_preferences'; caja-application.o:/home/robert/caja/src/../libcaja-private/caja-global-preferences.h:225: first …
```
=> Fix build using gcc 10 -fno-common flag

src/file-manager/fm-directory-view.h
In the `configure.ac` file, we defined that GLIB requires version 2.58.1, It can be safely droped here.
```
m4_define(glib_minver,                 2.58.1)
```
=> Drop GLIB version check

src/caja-desktop-window.c, src/caja-spatial-window.c
Even if we think that the desktop window title is never seen, it is used
by the window selector in "all windows" mode and speech synthesis.
=> Set a real title on the desktop window (as provided to ATK)

libcaja-private/caja-module.c
`CAJA_EXTENSION_DIRS` is a list of directories where caja extensions are looked for. It is needed for distributions like [NixOS](https://nixos.org/) that do not install all extensions in the same directory. In NixOS each package is installed in a self contained directory.
=> Look for caja extensions at $CAJA_EXTENSION_DIRS

HACKING
Updating the link of caja.
The old link generated a 404 error.
=> Updating the link of caja

libcaja-private/caja-undostack-manager.c
Fix https://github.com/mate-desktop/caja/issues/1106
Remove data loss threat from https://github.com/mate-desktop/caja/issues/1353 by preventing silent deletion of files in all cases except where user has turned off  "Ask before emptying trash or deleting files"
Use the general case  `caja_file_operations_delete` when undo operations involve deleting a file in all cases, as this respects "Ask before emptying trash or deleting files". Remove the direct use of `g_file_delete` and now unused variable `priv->confirm_delete` which was not being properly read or set for some reason. This is also shorter, simpler code and in the (default) case of " Ask before emptying trash or deleting files" being turned on is the intended codepath anyway.
Note that if the user cancels deletion of a …
=> Confirm undo if deleting

libcaja-private/caja-undostack-manager.c
Fix warning
`caja-undostack-manager.c:323: invalid property id 2 for "confirm-delete" of type 'GParamBoolean' in 'CajaUndoStackManager`' 
caused by newly unused property
=> fix runtime warning from newly unused code

libcaja-private/caja-file.c, src/caja-application.c, src/caja-desktop-window.c, src/caja-query-editor.c
Fixes the build warnings:
```
caja-file.c:3664:1: warning: no previous prototype for function 'caja_file_is_backup_file' [-Wmissing-prototypes]
caja-application.c:123:1: warning: no previous prototype for function 'caja_application_get_spatial_window_list' [-Wmissing-prototypes]
caja-application.c:214:1: warning: no previous prototype for function 'caja_application_smclient_startup' [-Wmissing-prototypes]
caja-application.c:730:1: warning: no previous prototype for function 'caja_application_open_desktop' [-Wmissing-prototypes]
caja-desktop-window.c:45:1: warning: no previous prototype for function 'caja_desktop_window_accessible_get_type' [-Wmissing-prototypes]
caja-query-editor.c:489:1: warning: no previous prototype for function 'xattr_tags_list_to_str' [-Wmissing-prototypes]
```
=> Fix -Wmissing-prototypes build warnings

src/caja-file-management-properties.c
Test:
Launch `caja-file-management-properties`, next select `Extensions` tab, finally enable/disable an extension.
Removed warning:
```
caja-file-management-properties.c:743:12: warning: the comparison will always evaluate as ‘true’ for the address of ‘iter’ will never be NULL [-Waddress]
743 |  if (&iter != NULL)
|            ^~
```
=> Remove the warning: the address of ‘iter’ will never be NULL

src/file-manager/fm-properties-window.c
fixes https://github.com/mate-desktop/caja/issues/1412
Unwanted arrows won't be shown and notebook-tabs mouse-scrolling works like before.
=> fm-properties: Don't show notebook arrows

configure.ac
Fix caja build fail with latest mate-submodules. see https://github.com/mate-desktop/mate-submodules/issues/12
=> add required libraries for libegg

libcaja-private/org.mate.caja.gschema.xml, po/POTFILES.in, src/Makefile.am, src/caja-application.c, src/caja-bookmarks-sidebar.c, src/caja-bookmarks-sidebar.h
One user requested to have a new sidebar added to Caja.  This sidebar shows only the user's own bookmarks.  When any bookmark in the sidebar is clicked on, Caja will open the bookmark in the current window and tab.  When the user middle-clicks the bookmark, Caja will open the bookmark in a new tab.
This feature was requested because the Places sidebar was a little too overcrowded for the requestor.
=> Add a "Bookmarks" sidebar to Caja

libcaja-private/caja-undostack-manager.c, src/caja-navigation-window-menus.c, src/caja-window.c, src/file-manager/fm-properties-window.c
```
find . \( -name '*.h' -o -name '*.c' \) -exec sed -i 's/[[:space:]]*$//' {} \;
find . \( -name '*.h' -o -name '*.c' \) -exec sed -i 's/\t*$//' {} \;
```
=> Remove trailing spaces/tabs

eel/eel-editable-label.c, libcaja-private/caja-icon-container.c
=> eel-editable-label: Consecutive break/return statements are unnecessary

libcaja-private/caja-link.c, libcaja-private/caja-link.h, src/file-manager/fm-directory-view.c
closes #1446
test:
- create the file test.html
```
$ cat <<EOF > test.html
<!DOCTYPE html>
<html>
<head>
<title>Remarks on the Quantum-Gravity effects of "Bean Pole" diversification in Mononucleosis patients in Developing Countries under Economic Conditions Prevalent during the Second half of the Twentieth Century, and Related Papers: a Summary - Remarks on the Quantum-Gravity effects of "Bean Pole" diversification in Mononucleosis patients in Developing Countries under Economic Conditions Prevalent during the Second half of the Twentieth Century, and Related Papers: a Summary</title>
</head>
<body>
</body>
</html>
EOF
```
- open test.html using FF
```
$ firefox test.html 
```
- drag-n-drop the document icon from FF location bar to desktop
=> fm-directory-view: Display an error message when a link could not be created

src/caja-window-manage-views.c, src/caja-window-menus.c, src/caja-window.c, src/caja-window.h
This has been a minor annoyance of mine, along with the notebook tab scroll removed from GTK3, because why make stuff convenient for the end user... Now we can have both!
=> Duplicate tabs using the scroll wheel

libcaja-private/caja-debug-log.c, test/test-eel-pixbuf-scale.c
Test 1 : see ~/caja-debug-log.txt
```
#!/bin/bash
cat << EOF > ~/caja-debug-log.conf
[debug log]
max lines = 1000
enable domains = async;GLog
EOF
```
Test 2 : call ./test/test-eel-pixbuf-scale FILENAME
```
./test/test-eel-pixbuf-scale /usr/share/pixmaps/fedora-logo.png
```
=> Remove the use of the gettimeofday function

libcaja-private/caja-file-operations.c
Dragging a file in caja onto the same active tab in tab bar shows a conflict resolution dialog. This is annoying, sometimes I start dragging an item, only to realize that it doesn't need to be moved, so I drop it onto the tab, subconsciously thinking it's the safest place to do so.
=> file-operations: don't attempt to move into the source dir

libcaja-private/caja-icon-container.c
```
caja-icon-container.c:842:1: warning: 'inline' is not at beginning of declaration [-Wold-style-declaration]
842 | static void inline
| ^~~~~~
```
=> caja-icon-container: warning -Wold-style-declaration

libcaja-private/caja-icon-info.h, src/file-manager/fm-icon-view.c
```
caja.make.log:/usr/include/glib-2.0/glib/gmacros.h:813:63: warning: comparison of unsigned expression in '< 0' is always false [-Wtype-limits]
caja.make.log-  813 | #define CLAMP(x, low, high)  (((x) > (high)) ? (high) : (((x) < (low)) ? (low) : (x)))
caja.make.log-      |                                                               ^
```
=> Remove warning -Wtype-limits

data/caja-browser.desktop.in.in
```
$ find -type f -name *.desktop -exec desktop-file-validate {} \;
./data/caja-browser.desktop: hint: value "GTK;System;Utility;Core;" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu
```
https://specifications.freedesktop.org/menu-spec/latest/apa.html
=> Fix desktop file validation warning

configure.ac
Test:
```
$ ./autogen.sh --prefix=/usr && grep GETTEXT_PACKAGE config.h
<cut>
#define GETTEXT_PACKAGE "caja"
```
=> build: set GETTEXT_PACKAGE=AC_PACKAGE_NAME

configure.ac, data/Makefile.am, data/caja.appdata.xml.in.in, po/POTFILES.in, src/caja-window-menus.c
Test:
```
$ grep PACKAGE_URL config.h
#define PACKAGE_URL "https://mate-desktop.org"
$ grep homepage data/caja.appdata.xml
<url type="homepage">https://mate-desktop.org</url>
```
- Set all [AC_INIT](https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Initializing-configure.html) fields including optional ones (configure.ac):
```
Macro: AC_INIT (package, version, [bug-report], [tarname], [url])
```
=> build: Use PACKAGE_URL variable

src/caja-window.c
```
src/caja-window.c:1530:16: style: Variable 'copy' is allocated memory that is never used. [unusedAllocatedMemory]
```
=> caja-window: Fix cppcheck warning unusedAllocatedMemory

src/caja-file-management-properties.c
Test: Change the icon captions to show using the combo boxes and read the gsettings value from the command line:
```
$ gsettings get org.mate.caja.icon-view captions
['type', 'size', 'date_modified']
```
Test:
```
$ cppcheck --enable=all --quiet . &> cppcheck.log && grep shadowArgument cppcheck.log
src/caja-file-management-properties.c:365:20: style: Local variable 'combo_box' shadows outer argument [shadowArgument]
```
=> cppcheck warning: Local variable 'combo_box' shadows outer argument

src/caja-pathbar.c
```
src/caja-pathbar.c:1590:10: warning: Either the condition 'if(button_data)' is redundant or there is possible null pointer dereference: button_data. [nullPointerRedundantCheck]
src/caja-pathbar.c:1596:54: warning: Either the condition 'if(button_data)' is redundant or there is possible null pointer dereference: button_data. [nullPointerRedundantCheck]
```
=> caja-pathbar: Fix cppcheck warning nullPointerRedundantCheck

src/caja-navigation-window-menus.c, src/caja-spatial-window.c, src/caja-window-menus.c, src/file-manager/fm-directory-view.c, src/file-manager/fm-icon-view.c
```
fm-directory-view.c:7389:32: warning: missing initializer for field ‘accelerator’ of ‘GtkActionEntry’ {aka ‘const struct _GtkActionEntry’} [-Wmissing-field-initializers]
fm-directory-view.c:7391:34: warning: missing initializer for field ‘callback’ of ‘GtkActionEntry’ {aka ‘const struct _GtkActionEntry’} [-Wmissing-field-initializers]
fm-directory-view.c:7404:32: warning: missing initializer for field ‘accelerator’ of ‘GtkActionEntry’ {aka ‘const struct _GtkActionEntry’} [-Wmissing-field-initializers]
fm-directory-view.c:7468:32: warning: missing initializer for field ‘accelerator’ of ‘GtkActionEntry’ {aka ‘const struct _GtkActionEntry’} [-Wmissing-field-initializers]
fm-directory-view.c:7469:32: warning: missing initializer for field ‘accelerator’ of ‘GtkActionEntry’ {aka ‘const …
```
=> warning: missing initializer for a field of ‘GtkActionEntry’

src/caja-main.c
```
```
https://git.savannah.gnu.org/cgit/autoconf.git/tree/lib/autoconf/headers.m4#n358
=> No longer need to check the locale.h header as it's part of C90

libcaja-private/caja-dnd.c, libcaja-private/caja-file-utilities.c, libcaja-private/caja-file-utilities.h
When files are dropped on the user home icon, it's file system data can be unavailable. This happens if the home folder has not been browsed before. Therefore, caja copies the files to the home folder even if home and desktop share the same file system.
On caja-dnd.c:458, the function caja_file_get_existing_by_uri returns a null target_file, causing check_same_fs to get a wrong result. The function with caja_file_get_by_uri returns a CajaFile, but with no filesystem_id.
=> Fix unknown filesystem on home icon dnd

libcaja-private/caja-directory.c
When creating a new file (using a template, for instance), file->
details->is_added could potentially be FALSE, and cause this file to
not be finalized along with other files if the view directory is
destroyed.
This can cause issues when re-entering that directory, with the file
being in an undefined state, and could prevent the view from fully
loading the location (this is identical behavior to that described
in https://github.com/mate-desktop/python-caja/pull/64.
To reproduce:
- Create an svg file and save in ~/Templates.
- Right-click, Create document-> svg file, name it whatever.
- Navigate out of the folder.
- Modify the file in a visible manner.
- Re-enter the folder, note that it never finishes loading.
Ref:
https://github.com/linuxmint/nemo/issues/2736
=> caja-directory.c: Fix memory leak.

libcaja-private/caja-dnd.c
```
caja-dnd.c:613:40: warning: format specifies type 'unsigned short' but the argument has type 'int' [-Wformat]
uri, x, y, w, h);
^
caja-dnd.c:613:43: warning: format specifies type 'unsigned short' but the argument has type 'int' [-Wformat]
uri, x, y, w, h);
^
```
=> caja-dnd: wrong type field in printf format string

src/caja-places-sidebar.c
Prevents the places sidebar right-click menu from having an incorrect height when selecting an item with a different amount of menu entries. This should fix #1473 / #1442.
Note that this also changes the behavior of right-clicking on a different sidebar item when the menu is already open: Instead of only closing the menu, the menu of the new item is opened immediately. I think I prefer it this way but I don't know if this is desired.
=> caja-places-sidebar: fix right-click menu height

eel/eel-background.c
```
Direct leak of 74 byte(s) in 1 object(s) allocated from:
#0 0x7f114a93f93f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7f1149627b7f in g_malloc ../glib/gmem.c:106
#2 0x7f1149627ec2 in g_malloc_n ../glib/gmem.c:344
#3 0x7f114964a1a5 in g_strdup ../glib/gstrfuncs.c:364
#4 0x7f11496779b4 in g_variant_dup_string ../glib/gvariant.c:1537
#5 0x7f11498d7d0d in g_settings_get_string ../gio/gsettings.c:1809
#6 0x6b06bf in eel_bg_load_from_gsettings /home/robert/builddir.gcc/caja/eel/eel-background.c:1004
#7 0x5bf10e in caja_connect_desktop_background_to_settings /home/robert/builddir.gcc/caja/libcaja-private/caja-directory-background.c:398
#8 0x53706f in fm_icon_view_begin_loading /home/robert/builddir.gcc/caja/src/file-manager/fm-icon-view.c:1348
#9 0x7f1149735f4f in …
```
=> eel-background: fix memory leak

src/file-manager/fm-directory-view.c
```
LeakSanitizer: detected memory leaks
Direct leak of 13 byte(s) in 1 object(s) allocated from:
#0 0x7f7d6c7da93f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7f7d6b4b94ff in g_malloc ../glib/gmem.c:106
#2 0x7f7d6b4b9842 in g_malloc_n ../glib/gmem.c:344
#3 0x7f7d6b4dc436 in g_strconcat ../glib/gstrfuncs.c:629
#4 0x7f7d6b481d65 in g_escape_file_uri ../glib/gconvert.c:1510
#5 0x7f7d6b481c98 in g_filename_to_uri ../glib/gconvert.c:1835
#6 0x7f7d6b7c4aa4 in g_local_file_get_uri ../gio/glocalfile.c:284
#7 0x7f7d6b688495 in g_file_get_uri ../gio/gfile.c:645
#8 0x5c0f08 in caja_directory_get_uri /home/robert/builddir.gcc/caja/libcaja-private/caja-directory.c:442
#9 0x52800e in fm_directory_view_get_uri /home/robert/builddir.gcc/caja/src/file-manager/fm-directory-view.c:10307
#10 …
```
=> fm-directory-view: fix memory leak

src/caja-sidebar-title.c
```
LeakSanitizer: detected memory leaks
```
```
Direct leak of 26 byte(s) in 2 object(s) allocated from:
#0 0x7f8f74d1f93f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7f8f739fe4ff in g_malloc ../glib/gmem.c:106
#2 0x7f8f739fe842 in g_malloc_n ../glib/gmem.c:344
#3 0x7f8f73a20d85 in g_strdup ../glib/gstrfuncs.c:364
#4 0x4c6c10 in override_title_font /home/robert/builddir.gcc/caja/src/caja-sidebar-title.c:432
#5 0x4c73bf in update_title_font /home/robert/builddir.gcc/caja/src/caja-sidebar-title.c:513
#6 0x4c7569 in update_title /home/robert/builddir.gcc/caja/src/caja-sidebar-title.c:533
#7 0x4c81f8 in update_all /home/robert/builddir.gcc/caja/src/caja-sidebar-title.c:737
#8 0x4c85fd in caja_sidebar_title_set_file /home/robert/builddir.gcc/caja/src/caja-sidebar-title.c:776
#9 …
```
=> caja-sidebar-title: fix memory leak

src/caja-property-browser.c
Test: Drag & drop a color from Backgrounds & Emblems dialog.
```
caja-property-browser.c:828:35: warning: implicit conversion loses integer precision: 'guint16' (aka 'unsigned short') to 'char' [-Wimplicit-int-conversion]
*row_pixels++ = color.red;
~ ~~~~~~^~~
caja-property-browser.c:829:35: warning: implicit conversion loses integer precision: 'guint16' (aka 'unsigned short') to 'char' [-Wimplicit-int-conversion]
*row_pixels++ = color.green;
~ ~~~~~~^~~~~
caja-property-browser.c:830:35: warning: implicit conversion loses integer precision: 'guint16' (aka 'unsigned short') to 'char' [-Wimplicit-int-conversion]
*row_pixels++ = color.blue;
~ ~~~~~~^~~~
caja-property-browser.c:831:29: warning: implicit conversion from 'int' to 'char' changes value from 255 to -1 [-Wconstant-conversion] …
```
=> caja-property-browser: Fix build warning -Wconstant-conversion / 'gdk_color_parse' is deprecated

configure.ac
it was not handled correctly
in the generated configure file this string was left unchanged
=> remove '-' from a m4_define

libcaja-private/caja-file-operations.c
```
caja-file-operations.c:4048:45: warning: overlapping comparisons always evaluate to true [-Wtautological-overlap-compare]
} else if (response != GTK_RESPONSE_CANCEL ||
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
```
=> caja-file-operations: overlapping comparisons always evaluate to true

eel/eel-canvas-rect-ellipse.c, eel/eel-editable-label.c, libcaja-private/caja-desktop-icon-file.c, libcaja-private/caja-directory-async.c, libcaja-private/caja-file.c, libcaja-private/caja-icon-canvas-item.c, libcaja-private/caja-icon-container.c, src/caja-pathbar.c, src/file-manager/fm-list-view.c, src/file-manager/fm-tree-model.c
```
CFLAGS="-Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum && make &> make.log
```
```
eel-canvas-rect-ellipse.c:207:24: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'unsigned int' [-Wsign-conversion]
eel-canvas-rect-ellipse.c:217:27: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'unsigned int' [-Wsign-conversion]
eel-editable-label.c:767:31: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
eel-editable-label.c:793:23: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
eel-editable-label.c:1003:42: …
```
=> Fix implicit conversion changes signedness: 'gboolean' to 'guint'

libcaja-private/caja-bookmark.c
```
git submodule init
git submodule update --recursive --remote
CFLAGS="-g -O0 -Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum && make
```
```
caja-bookmark.c:333:12: warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]
return !g_icon_equal (bookmark->details->icon, new_icon) != 0;
^                                                 ~~
caja-bookmark.c:333:12: note: add parentheses after the '!' to evaluate the comparison first
return !g_icon_equal (bookmark->details->icon, new_icon) != 0;
^
(                                                    )
caja-bookmark.c:333:12: note: add parentheses around left hand side expression to silence this warning
return …
```
=> caja-bookmark: Fix build warning -Wlogical-not-parentheses

libcaja-private/caja-file-conflict-dialog.c
Fix #1630.
This contains 3 separate but fairly closely related changes (see each commit for details):
1) Fix reference to objects by releasing them in `dispose()` as we ought to instead of waiting for `finalize()`.  This is the real fix, and is the right thing to do in the GObject world: no object is supposed to hold a reference to any other object after `dispose()`.
2) Simplification of the icon update code, which optimizes it as well and allows for improving safety in 3 -- thanks @rbuj
3) thanks to 2, make use of `g_signal_connect_object()` to improve safety of the handler by making sure all parameters are valid at signal dispatch time.
1 alone is enough of a fix, but 2 is a nice improvement of the code, and 3 makes things safer.  Actually, 2+3 alone are also a fix for #1630, although …
=> Fix file conflict dialog crashes

libcaja-private/org.mate.caja.gschema.xml, src/file-manager/fm-list-view.c
This patch resolves three related issues:
The first issue was that the GSettings schema for Caja did not include an entry to sort by the "btime", or creation date, of files.  If the user chose such an option in the Caja Preferences, GSettings would produce a warning (often out-of-sight, as it was usually redirected into the user's .xsession-errors file), and Caja would not actually change the default sort-order of files.  This patch adds the btime as a valid setting in the schema.
The second issue was that, because of the above (an entry in the settings schema was missing), some of the alternative sort orders listed in the schema (everything after and including "atime") were not assigned the same numbers as the sort orders listed elsewhere in the Caja source code.  Specifically, in icon- …
=> Document and fix default-sort-order preference

eel/eel-canvas-rect-ellipse.c, eel/eel-canvas.c, libcaja-private/caja-icon-container.c, libcaja-private/caja-icon-info.c, src/file-manager/fm-properties-window.c, test/test-eel-pixbuf-scale.c
```
eel-canvas.c:2376:16: warning: cast from function call of type 'gdouble' (aka 'double') to non-matching type 'int' [-Wbad-function-cast]
if (((int) gtk_adjustment_get_value (hadjustment)) != cx)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
eel-canvas.c:2382:16: warning: cast from function call of type 'gdouble' (aka 'double') to non-matching type 'int' [-Wbad-function-cast]
if (((int) gtk_adjustment_get_value (vadjustment)) != cy)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--
eel-canvas-rect-ellipse.c:738:34: warning: cast from function call of type 'double' to non-matching type 'int' [-Wbad-function-cast]
width_pixels = (int) floor (re->width * re->item.canvas->pixels_per_unit + 0.5);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--
caja-icon-container.c:7993:32: warning: cast …
```
=> Fix build warning -Wbad-function-cast

eel/eel-accessibility.c, eel/eel-canvas-rect-ellipse.c, eel/eel-canvas.c, eel/eel-labeled-image.c, libcaja-extension/caja-column-provider.c, libcaja-extension/caja-configurable.c, libcaja-extension/caja-file-info.c, libcaja-extension/caja-info-provider.c, libcaja-extension/caja-location-widget-provider.c, libcaja-extension/caja-menu-item.c, libcaja-extension/caja-menu-provider.c, libcaja-extension/caja-property-page-provider.c, libcaja-extension/caja-property-page.c, libcaja-extension/caja-widget-view-provider.c, libcaja-private/caja-query.c, libcaja-private/caja-sidebar-provider.c, libcaja-private/caja-sidebar.c, libcaja-private/caja-view.c, libcaja-private/caja-window-info.c, libcaja-private/caja-window-slot-info.c, src/caja-application.c
```
git submodule init
git submodule update --recursive --remote
CFLAGS="-g -O0 -Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum && make
```
```
eel-accessibility.c:226:9: warning: missing field 'class_data' initializer [-Wmissing-field-initializers]
eel-canvas.c:141:9: warning: missing field 'value_table' initializer [-Wmissing-field-initializers]
eel-canvas.c:1260:9: warning: missing field 'value_table' initializer [-Wmissing-field-initializers]
eel-canvas.c:1855:9: warning: missing field 'value_table' initializer [-Wmissing-field-initializers]
eel-canvas-rect-ellipse.c:105:9: warning: missing field 'value_table' initializer [-Wmissing-field-initializers]
eel-canvas-rect-ellipse.c:469:9: warning: …
```
=> Fix build warning -Wmissing-field-initializers

libcaja-private/caja-bookmark.c, src/caja-bookmarks-sidebar.c
When the uri is changed, caja automatically checks whether the uri exists in the sidebar to select it. It always checks in  places, bookmarks, ... . If the bookmarks list is empty, then some critical error messages are obtained such as:
```
GLib-GIO-CRITICAL **: 08:40:56.086: g_file_get_uri: assertion 'G_IS_FILE (file)' failed
```
When the bookmarks list is empty, the variable bookmark is NULL:
https://github.com/mate-desktop/caja/blob/141440bf89af9df9b64f77ac3a1c0fc63b768989/src/caja-bookmarks-sidebar.c#L332-L343
=> caja-bookmark: 'caja_bookmark_get_uri (CajaBookmark *)' may return NULL

libcaja-private/caja-extensions.c
enable caja logging
```
$ cat << EOF > ~/caja-debug-log.conf
[debug log]
max lines = 1000
enable domains = async;GLog
EOF
```
restart caja
```
$ killall -9 caja
```
check caja log
```
$ kill -s SIGUSR1 $(pgrep caja) && grep "Error loading keys from file" ~/caja-debug-log.txt
0x2585090 2022/07/30 09:34:05.955040 (USER): Error loading keys from file "/usr/share/caja/extensions/libcaja-seahorse.caja-extension": El fitxer o directori no existeix
0x2585090 2022/07/30 09:34:05.967419 (USER): Error loading keys from file "/usr/share/caja/extensions/libcaja-actions-menu.caja-extension": El fitxer o directori no existeix
0x2585090 2022/07/30 09:34:05.967953 (USER): Error loading keys from file "/usr/share/caja/extensions/libcaja-actions-tracker.caja-extension": El fitxer o directori no existeix …
```
=> caja-extensions: print filename when caja failed to open keys file

data/caja-browser.desktop.in.in
This PR enables the displaying of Caja (as a file manager) for use in Budgie Desktop and XFCE. Prior to this commit, it would only be able accessible in MATE or with downstreams like Fedora patching in the support. The addition of these is important as file managers such as Nautilus adopt libadwaita and begin to directly come into conflict with user theming choices.
=> Enable showing in Budgie Desktop and XFCE

libcaja-private/caja-icon-dnd.c, libcaja-private/caja-mime-application-chooser.c, libcaja-private/caja-search-directory-file.c, libcaja-private/caja-search-directory-file.h, libcaja-private/caja-search-directory.c, libcaja-private/caja-search-engine-simple.c, libcaja-private/caja-search-engine.c, libcaja-private/caja-search-engine.h, src/file-manager/fm-icon-view.c, src/file-manager/fm-properties-window.c, src/file-manager/fm-tree-model.c, src/file-manager/fm-tree-view.c
This removes various unused code, based on a [cppcheck report](https://caja.mate-desktop.dev/2022-11-23-174623-5790-cppcheck@ae663c369cf2_desktop-no-overflow/).  I carefully checked everything the best I could (not simply trusting the reports), but most of it was accurate.  Most stuff predates MATE repository so I can only guess they are leftovers from some old refactoring.
=> Remove dead code found by cppcheck

libcaja-private/caja-icon-container.h
This is actually an opaque type, and there is no definition of struct CajaIconData anywhere.  This actually doesn't change anything as the non-existent struct is equivalent to any other incomplete type, and works fine so long as the pointers are not dereferenced using that incomplete type.
However, change this to an explicit `void` to make it clear it's an opaque pointer and stop people from looking for a struct CajaIconData that is nowhere to be found.
---
Alternatively we could replace all use of `CajaIconData*` with `gpointer`, but that's a much more intrusive change.
=> Make CajaIconData type less confusing

libcaja-private/caja-icon-container.c
Properly update the icon data before placing the icon, because positioning might depend on full icon contents on the desktop, whereas updating contents don't care about position.
When an icon position overflows the desktop area, it is clamped to stay in the visible area, but this computation depends on accurate icon and label sizes, which is only available when the icon is fully loaded.
Fix the code to first load the contents and then position instead of the other way around, which was actually trivial.
Note that visible positions were most often correct anyway for two reasons:
1. Most of the time icons do not overflow, as they are positioned on the final desktop size anyway.  It however can easily happen reducing monitor resolution or increasing desktop view zoom. (see also #1676)
2. A …
=> icon view: Fix positioning overflowing icons on the desktop

libcaja-private/caja-dnd.c
`p` actually could never be `0` (because of the NULL check on the `memchr()` call), but the intended behavior is `*p == '\0'`: the containing condition checks for either a truncated data (`*p == '\0'`) or no geometry information (`*p == '\n'`).
I replaced the check to be `*p != '\n'` instead of `*p == '\0'` to make this more robust as the actual issue is anything but a newline, the fact it can only be a NUL otherwise is incidental to the enclosing check, but not really relevant at this level.  This is also in line with the actual error message.
Found by cppcheck: https://caja.mate-desktop.dev/2022-11-23-174623-5790-cppcheck@ae663c369cf2_desktop-no-overflow/16.html#line-204
----
Normally you won't see any change in any case, unless you manage to drop invalid data somehow.
=> Fix handling of invalid x-special/mate-icon-list drops

libcaja-private/caja-directory-async.c
This change will make the directory properties info always count "hidden" dotfiles in the count and size.
based on https://gitlab.gnome.org/GNOME/nautilus/-/merge_requests/821/diffs
fixes #527, fixes #738
=> directory: Include hidden files in properties window totals

libcaja-private/caja-file.c
If informal date format is used, the yesterday/today ranges of 48/24 hours apply to the end of the current day, not to the current instant.
Fixes a regression introduced by 476f56a25be636970b336d525a7766b6d1eb3fff. Fixes #1621.
=> caja-file: fix yesterday/today informal date bug

libcaja-private/caja-file.c
If informal date format is used, for future dates the today time format has been used by mistake, instead of the general time format.
=> caja-file: fix future informal date bug

src/caja-desktop-window.c
Fix the xrandr error. Here use a gdk_screen_get_width/height func to get the right changed size
just like nautilus-desktop do. 
Also fix https://github.com/mate-desktop/caja/issues/1096
=> caja-desktop-window: Fix the xrandr error

src/caja-desktop-window.c
In x11 we can anchor the desktop size to the root window instead of the screen or (possibly multiple)monitors
=> Replace deprecated code from xrandr fix

.build.yml, configure.ac, eel/eel-background.c, eel/eel-editable-label.c, eel/eel-gtk-extensions.c, src/Makefile.am, src/caja-application.c, src/caja-desktop-window.c, src/file-manager/fm-desktop-icon-view.c
*Uses gtk-layer-shell to keep the desktop always on the bottom *Uses gtk-layer-shell to keep the desktop on all workpaces *Depends on two changes in mate-desktop package
*We can later make wayland support optional here due to new dependency on gtk-layer-shell
*Depends on https://github.com/mate-desktop/mate-desktop/pull/558
=> wayland: initial support for showing the desktop

libcaja-private/caja-directory-async.c, libcaja-private/caja-file.c
=> fix gfile sort and symlink warnings w glib 2.76 or later

src/caja-application.c
```
caja-application.c:1557:11: error: implicit declaration of function ‘xmlReadMemory’; did you mean ‘xmlInitMemory’? [-Werror=implicit-function-declaration]
1557 |     doc = xmlReadMemory (data, strlen (data), NULL, "UTF-8", 0);
|           ^~~~~~~~~~~~~
|           xmlInitMemory
caja-application.c:1557:9: warning: assignment to ‘xmlDocPtr’ {aka ‘struct _xmlDoc *’} from ‘int’ makes pointerfrom integer without a cast [-Wint-conversion]
1557 |     doc = xmlReadMemory (data, strlen (data), NULL, "UTF-8", 0);
|         ^
```
Building caja with commit from PR for fedora-rawhide at koji buildserver works fine.
https://src.fedoraproject.org/rpms/caja/blob/rawhide/f/caja_0001-fix-building-with-libxml-2.12.0.patch
https://koji.fedoraproject.org/koji/taskinfo?taskID=109410799
=> fix building with libxml 2.12.0

src/file-manager/fm-icon-view.c
When icon positions are locked, do not show "Organize Desktop by Name" in the desktop context menu
=> Do not show "Organize Desktop by Name" when desktop icons are locked

src/caja-spatial-window.c
*When under wayland, silence `caja_spatial_window_show: assertion 'location != NULL' failed` warning
*The startup sequence is not the same with wlroots and the location isn't ready yet 
*Using gtk_widget_show instead of gtk_widget_realize in caja-desktop-window.c generates this warning
=> wayland desktop: suppress spatial window warning

eel/eel-background.c, libcaja-private/caja-icon-container.c, src/caja-desktop-window.c, src/file-manager/Makefile.am, src/file-manager/fm-desktop-icon-view.c, src/file-manager/fm-desktop-wayland-bg-dialog.c, src/file-manager/fm-desktop-wayland-bg-dialog.h
*Set the background when in wayland using a cssprovider 
*Read the bg image filename from and save it to gsettings 
*Listen for the bg image filename changing
*Works from caja's "Change Desktop Background" menu item, from caja-extensions "set as wallpaper" and with changing the background in dconf-editor.
=> Manage desktop backgrounds when running in wayland

src/file-manager/fm-desktop-wayland-bg-dialog.c
Wayland-background-dialog: fix memory leaks, check for valid GtkImage for the preview before attempting to use it.
=> Wl bgleaks fixes

src/file-manager/fm-desktop-icon-view.c
*In the wayland session, we now have mate-settings-daemon with GDK_BACKEND=x11 
*We need it to control theming in xwayland apps
*So we can now use mate-appearance-properties to set the desktop background when it is running
*To support standalone use of caja in any wayland session  when mate-settings-daemon is not running or when mate-control-center is not installed, we use the standalone wayland dialog in those cases
=> wayland background: use mate-appearance-properties if we can

src/caja-window.c
Ensure that nagivation and spatial windows can be moved and resized when running under wayland with CSD enabled, note that CSD is the default in many compositors and forced in some. 
Also note that in wayfire, using CSD will pick up the GTK theme's decorations which will look like they do for windows that do not use headerbars (such as all MATE apps) in Mutter. This gives far better support for the MATE themes than firedecor or similar SSD decorators for wayfire. We read the port of the metacity theme to GTK and without a GtkHeaderBar we get normal titlebar theming and dimensions unless the theme itself has an issue.
=> wayland: ensure windows can be moved and resized  if compositor is using CSD

libcaja-private/caja-file-operations.c
Fixes the condition for showing an estimate of the remaining duration in case a copy operation is queued, aligning to the delete operation case.
=> caja-file-operations: fix estimate for queued copy

libcaja-private/caja-icon-container.c
* Do not attempt to unref or destroy a child of a container
*In GTK 3 at least, GtkContainers automatically destroy child widgets when destroyed
*Trying to do this with glib 2.82 or later causes sporadic crashes on closing a navigation window at least in wayland.
=> wayland/window closing: avoid a crash on gtk_widget_destroy

libcaja-private/caja-file.c
The G_FILE_ATTRIBUTE_STANDARD_CONTENT_TYPE attribute doesn't have to be always set. See https://gitlab.gnome.org/GNOME/gvfs/-/merge_requests/68 for more details. In that case, Caja fallbacks to the "application/octet-stream" type, which causes issues when opening the files. Let's fallback to the "standard::fast-content-type" attribute instead to fix issues when opening such files.
Imported from Nautilus commit: https://gitlab.gnome.org/GNOME/nautilus/-/commit/0e5978035b0fc87c91d7b93ed79c64d51b6d6825
Fixes #1840.
@sijskes could you give this a spin and see if it fixes it?  It's simply an import of the Nautilus fix, but it might just do it.
=> file: Fallback to fast-content-type if content-type is not set

src/caja-desktop-window.c
*Force caja on wayland to be the true background layer so windows like conky always render on top of it
*without this clicking on the desktop window raises it over conky and hides it
=> wayland: set desktop layer as background not bottom
