mate-desktop/caja

src/caja-places-sidebar.c

This reverts commit 910b9141ac634a86d8f53fda534e33787a160efb.

Revert "places-sidebar: allow dropping of files to bookmarks"

---

eel/eel-canvas.c

adapted from https://github.com/linuxmint/nemo/commit/d5377cfd53034b6ab5588376322126f48782ec59
(thanks to @mtwebster and nautilus developer who did the original commit)
fixes https://github.com/mate-desktop/caja/issues/376
Works fine in Debian Testing which currently has GTK+ 3.14.13.
Thanks to @NiceandGently for showing me the right place in the code :grinning: 
@flexiondotorg: if you can, please test it in GTK+3 build.

[GTK+3] eel: fix bad positioning of rename window in certain cases

---

src/caja-main.c

thanks to @mtwebster (https://github.com/linuxmint/nemo/commit/acabbaf6ca8e5ffc29851d766339c602777c4427)
and @tarakbumba (https://github.com/mate-desktop/caja/pull/409)
closes https://github.com/mate-desktop/caja/pull/409
It works perfectly for me in Debian Jessie, but I'd like some more testing before pushing it to master.

don't manage desktop and exit with last window when either running as root or on other desktops

---

eel/eel-canvas-rect-ellipse.c
eel/eel-canvas-rect-ellipse.h
eel/eel-canvas.c
eel/eel-editable-label.c
eel/eel-gdk-extensions.c
eel/eel-gdk-extensions.h
eel/eel-gdk-pixbuf-extensions.c
eel/eel-gdk-pixbuf-extensions.h
eel/eel-graphic-effects.c
eel/eel-graphic-effects.h
eel/eel-gtk-extensions.c
libcaja-private/caja-file-conflict-dialog.c
libcaja-private/caja-icon-canvas-item.c
libcaja-private/caja-icon-container.c
libcaja-private/caja-icon-dnd.c
libcaja-private/caja-icon-info.c
libcaja-private/caja-icon-private.h
libcaja-private/caja-tree-view-drag-dest.c
src/caja-location-bar.c
src/caja-notebook.c
src/caja-places-sidebar.c
src/caja-sidebar-title.c
src/caja-spatial-window.c
src/caja-window.c
src/file-manager/fm-list-model.c
src/file-manager/fm-list-view.c
src/file-manager/fm-properties-window.c
src/file-manager/fm-tree-model.c

- port gtk_style --> gtk_style_context (most files)
- port GdkColor --> GdkRGBA (most files)
- fixes https://github.com/mate-desktop/caja/issues/445
- fixes https://github.com/mate-desktop/caja/issues/81 (gtk3)
- fixes selected color does not change with gtk theme change (gtk3)
Some theme changes are needed, i will post this later and update our themes.
I know this are a lot of commits and i don't want push this to master w/o testing.
@monsta 
@flexiondotorg 
@lukefromdc
Please test, hopfully i don't introduce a reggression.
Also for gtk2, 2 commits affects gtk2 too.

port to gtk_style_context and other fixes

---

eel/eel-canvas.c
eel/eel-canvas.h
libcaja-private/caja-dnd.c
libcaja-private/caja-icon-container.c
libcaja-private/caja-icon-dnd.c
libcaja-private/caja-tree-view-drag-dest.c
src/file-manager/fm-desktop-icon-view.c

@XRevan86
Can you do the review please, as you did the port in mate-panel?
@monsta @flexiondotorg @lukefromdc 
Please test.
Most commits are from nautilus.

replace deprecated device_manager

---

eel/eel-gtk-extensions.c
eel/eel-gtk-extensions.h
libcaja-private/caja-file-conflict-dialog.c
libcaja-private/caja-icon-container.c
libcaja-private/caja-open-with-dialog.c
src/caja-connect-server-dialog.c
src/caja-notebook.c
src/caja-search-bar.c
src/file-manager/fm-list-view.c
src/file-manager/fm-properties-window.c

Well, i was quite busy ;)
@monsta @flexiondotorg @lukefromdc 
As always, please test and review.

deprecations fixes

---

configure.ac
src/caja-application.c
src/caja-application.h
src/caja-bookmarks-window.c
src/caja-connect-server-dialog-nonmain.c
src/caja-location-bar.c
src/caja-main.c
src/caja-navigation-window-menus.c
src/caja-navigation-window.c
src/caja-places-sidebar.c
src/caja-spatial-window.c
src/caja-window-manage-views.c
src/caja-window.c

based on https://github.com/emanuele-f/caja/commit/4b36a91af42d8efe0f594a95d28ab8448fd73b31
but including 
https://github.com/mate-desktop/caja/pull/660
and https://github.com/emanuele-f/caja/pull/1

Fix GTK2 builds

---

libcaja-private/caja-file-conflict-dialog.c

based on nautilus commit:
https://git.gnome.org/browse/nautilus/commit/?id=b370817
Fixes partially #535

Improved merge folder dialog

---

libcaja-private/caja-icon-container.c

Fix https://github.com/mate-desktop/caja/issues/671
Apply https://git.gnome.org/browse/nautilus/commit/?id=40be4b85f51fc7b192ef7421b2ede27954997cc8

Fix keyboard-down wraparound on compact view

---

src/file-manager/fm-list-view.c

fixes https://github.com/mate-desktop/caja/issues/649
adapted from:
https://git.gnome.org/browse/nautilus/commit/?id=e19f7cb3fec1e6c884d1741c3c00916c65ab035f

show/hide columns instead of appending/removing them

---

eel/eel-canvas.c
libcaja-private/caja-icon-container.c

Those commits are all bug fixes for gtk3 which belongs in 1.16 branch.
I made them all gtk3 only as i don't know if they are good for gtk2.
Not sure who have 1.16 with mate gtk3 running somewhere.
Please test.

fix scrolling and renaming in large folders 1.16

---

src/caja-bookmark-list.c

If it doesn't exist fallback to reading from the old location but
always write to the new location.
https://bugzilla.gnome.org/show_bug.cgi?id=674986
taken from:
https://git.gnome.org/browse/nautilus/commit/?id=ed90577
This is better since we use gtk3 filechooser. Filechooser use gtk3 location and you will never seen bookmarks from ~.gtk-bookmarks  there.
For a new installation or new user account this will make no different to old behaviour.
For a existing account the user needs to export the old bookmarks to new file.
Probably it's possible to read from both locations, but i don't think it's good to use 2 locations.
Also, we sync our location with nemo or nautilus. Helpful if users switch to using MATE.

Use gtk+-3 bookmarks location

---

src/caja-bookmarks-window.c
src/caja-connect-server-dialog.c
src/caja-file-management-properties.c
src/caja-location-dialog.c
src/caja-property-browser.c
src/caja-window-menus.c
src/file-manager/fm-directory-view.c
src/file-manager/fm-properties-window.c

don't use deprecated gtk_show_uri

---

eel/eel-background.c

Fixes https://github.com/mate-desktop/caja/pull/824#issuecomment-323568583
@raveit65 @lukefromdc please test

Fix: Scaling the desktop wallpaper doesn't work

---

src/file-manager/fm-directory-view.c

Fixes https://github.com/mate-desktop/caja/issues/509

Fix: wrong <Shift+Del> behavior while renaming files

---

src/caja-window-slot.c

this should be pretty straightforward.

Fix for #719 (tasklist icon change when opening new tab)

---

eel/eel-stock-dialogs.c
libcaja-private/caja-mime-actions.c
src/caja-location-bar.c

I don't know how to show these dialogs

avoid eel_run_simple_dialog with stock ids

---

libcaja-private/caja-search-directory.c

modify code error: end the statement with a semicolon

modify code error: end the statement with a semicolon

---

libcaja-private/caja-bookmark.c

Fixes https://github.com/mate-desktop/caja/pull/962#issuecomment-389114129

caja-bookmark.c: Fix icons in bookmarks

---

eel/eel-gtk-extensions.c
src/caja-sidebar-title.c

I just removed related code, I don't see differences

avoid deprecated 'gtk_widget_override_font'

---

src/caja-desktop-window.c

Fixes https://github.com/mate-desktop/caja/pull/1005#issuecomment-394805519
I don't know what means, but I keep the same comment here as before:
https://github.com/mate-desktop/caja/pull/1005/files#diff-5b74cc5e4b5c15d0430f0921ed104c3bL155

caja-desktop-window.c: Fix: caja crashes unexpectedly

---

src/caja-location-bar.c

and avoid deprecated 'gtk_widget_override_background_color'
The expected with this PR, exactly the same behavior like caja 1.8.2 (gtk2)
With this PR, see the video:
[out-65.ogv.zip](https://github.com/mate-desktop/caja/files/2134993/out-65.ogv.zip)
seems we have that issue since the gtk3 migration, I think, the color never changes, and this PR is the fix

caja-location-bar: Fix: change background color based on activity state

---

src/caja-navigation-window-pane.c

pathbar: Activate pane when changing location

---

src/caja-application.c

Remove two dead code blocks and fix a memory leak left over from last commit

Remove dead code, fix a memory leak

---

libcaja-private/caja-directory.c

@raveit65 
Fixed running caja_self_check_directory failed, see #1079

GSettings should init beforce use it.

---

libcaja-private/caja-bookmark.c

'g_strconcat' needs to be freed

caja-bookmark: Fix memory leak

---

libcaja-private/caja-progress-info.c
libcaja-private/org.mate.caja.gschema.xml

Closes https://github.com/mate-desktop/caja/issues/1093

caja-progress-info: show notifications with the gsettings key

---

eel/eel-background.c
eel/eel-image-table.c
eel/eel-labeled-image.c
eel/eel-wrap-table.c
libegg/eggsmclient.c

Replace `G_DEFINE_TYPE_WITH_CODE` with `G_DEFINE_TYPE_WITH_PRIVATE` macro.

[eel][libegg] Use G_DEFINE_TYPE_WITH_PRIVATE macro

---

libcaja-extension/caja-menu.c
src/caja-application.c
src/caja-application.h

Please review and test it, thanks.

Avoid deprecated g_type_class_add_private

---

libcaja-private/caja-query.c
libcaja-private/caja-query.h
libcaja-private/caja-search-engine-simple.c
src/caja-query-editor.c

Thanks for Leslie Zhai's patch, UI like this:
Please review and test it, thanks.

Support querying files by modification time and size

---

src/caja-connect-server-operation.c
src/caja-connect-server-operation.h
src/caja-desktop-window.c
src/caja-desktop-window.h
src/caja-image-properties-page.c
src/caja-image-properties-page.h

Changed CajaConnectServerOperation, CajaDesktopWindow and CajaImagePropertiesPage

Avoid deprecated g_type_class_add_private under src

---

libcaja-private/caja-desktop-link.c
libcaja-private/caja-desktop-link.h
libcaja-private/caja-directory-private.h
libcaja-private/caja-directory.c
libcaja-private/caja-directory.h

Changed CajaDesktopLink, CajaDirectoryAsync and CajaDirectory

Avoid deprecated g_type_class_add_private under libcaja-private

---

Makefile.am
configure.ac
libcaja-private/caja-icon-container.c
src/Makefile.am

Fixed make distcheck, see #1129

Add --disable-self-check for configure

---

.travis.yml

After merge #1133 , this can works fine.

update travis to support archlinux and enable distcheck

---

configure.ac

The help string is error on #1133

fixed the help string of --disable-self-check

---

.travis.yml
Makefile.am
configure.ac
libcaja-private/caja-icon-container.c
src/Makefile.am

back port of https://github.com/mate-desktop/caja/commit/91f1dc66b6f56e57734d3048501a6c4679331290 and https://github.com/mate-desktop/caja/commit/2d595142c4c3f15391d71bf25e48e5905804ba94

Travis 1.20 backports

---

libcaja-private/caja-file.c

Fixes https://github.com/mate-desktop/caja/issues/1183

caja-file: Fix incomplete file replacement dialog

---

eel/eel-glib-extensions.c
eel/eel-glib-extensions.h
libcaja-private/caja-file-operations.c
libcaja-private/caja-progress-info.c
src/caja-window-manage-views.c
src/caja-window.c
src/file-manager/fm-directory-view.c

GNOME/nautilus@7af24a8
Replace
GList * eel_g_object_list_copy (GList *list)
with
g_list_copy_deep (list, (GCopyFunc) g_object_ref, NULL)

eel: remove g_object_list_copy

---

.travis.yml

This PR enables `cppcheck` static analyzer in the logs

travis: enable 'cppcheck'

---

libcaja-private/caja-progress-info.c

Fixes https://github.com/mate-desktop/caja/issues/845

caja-progress-info: add tooltips to file transfer dialog

---

src/caja-desktop-window.c
src/caja-navigation-action.c
src/caja-navigation-window-menus.c
src/caja-navigation-window.c
src/caja-spatial-window.c
src/caja-view-as-action.c
src/caja-window-bookmarks.c
src/caja-window-manage-views.c
src/caja-window-menus.c
src/caja-window-toolbars.c
src/caja-window.c
src/caja-zoom-action.c
src/file-manager/fm-icon-view.c
src/file-manager/fm-list-view.c

This make the build log finally readable.
Please review.

Silent gtk action 2

---

eel/eel-gtk-extensions.c
eel/eel-gtk-extensions.h
src/caja-file-management-properties.c
src/file-manager/fm-properties-window.c

Add scroll tabs with mouse wheel for file's properties and caja's preferences windows.

Add scroll tabs with mouse wheel

---

eel/eel-string.c

Fixes https://github.com/mate-desktop/caja/commit/312394dfa42c07a3afa5089c6e3e5b9a1c1001ae#commitcomment-34152266

eel-string: Fix 'make check'

---

src/file-manager/fm-list-model.c

Fixed #153, please test and review.

Show thumbnails in list view

---

src/caja-property-browser.c
src/caja-spatial-window.c
src/file-manager/fm-list-view.c

Please test.
new button menu in spartial mode:

Fix some deprecations

---

Makefile.am
data/Makefile.am
data/icons/Makefile.am
data/patterns/Makefile.am
docs/Makefile.am
docs/reference/Makefile.am
docs/reference/libcaja-extension/Makefile.am
eel/Makefile.am
git.mk
icons/Makefile.am
libcaja-extension/Makefile.am
libcaja-private/Makefile.am
libegg/Makefile.am
src/Makefile.am
src/file-manager/Makefile.am
test/Makefile.am

See https://raw.github.com/behdad/git.mk

add git.mk to generate .gitignore

---

src/caja-places-sidebar.c

caja-places-sidebar: add icon to "empty trash"

---

src/file-manager/fm-directory-view.c

fm-directory-view: add icon to "empty trash" into "File" menu

---

libcaja-private/caja-global-preferences.h
libcaja-private/org.mate.caja.gschema.xml
src/caja-file-management-properties.c
src/caja-file-management-properties.ui
src/file-manager/fm-list-model.c
src/ui-a11y.suppr

This PR fixed #26, please test and review.

Add preference option to hide icons in list view.

---

libcaja-private/caja-query.c
libcaja-private/caja-query.h
libcaja-private/caja-search-engine-simple.c
src/caja-query-editor.c

ODF files also supported via odt2txt

Support querying files by contained text

---

po/ko.po

See https://github.com/mate-desktop/caja/issues/1280

Update Korean translation which prevents a segfault on file move

---

po/ko.po

Fix Caja crashes on file move in Korean

---

libcaja-private/caja-progress-info.c

Fixes https://github.com/mate-desktop/caja/issues/1285
https://developer.gnome.org/libnotify/unstable/NotifyNotification.html
before:
later:

caja-progress-info: use NotifyNotification instead of GNotification

---

data/caja-autorun-software.desktop.in.in
data/caja-browser.desktop.in.in
data/caja-computer.desktop.in.in
data/caja-file-management-properties.desktop.in.in
data/caja-folder-handler.desktop.in.in
data/caja-home.desktop.in.in
data/caja.desktop.in.in
data/mate-network-scheme.desktop.in.in

Comments are based on:
https://github.com/GNOME/nautilus/blob/master/data/org.gnome.Nautilus.desktop.in.in

desktop files: Add comments for translators

---

.travis.yml

it is needed to build the files:
```
fm-empty-view.c 
fm-empty-view.h
```

Travis CI: 'autogen.sh' and 'scan-build' with '--enable-empty-view'

---

eel/eel-canvas.c
eel/eel-editable-label.c
libcaja-private/caja-directory-private.h
libcaja-private/caja-directory.c
libcaja-private/caja-icon-container.c
libcaja-private/caja-keep-last-vertical-box.c
libcaja-private/caja-query.c
libcaja-private/caja-search-engine-beagle.c
libcaja-private/caja-search-engine-simple.c
libcaja-private/caja-search-engine-tracker.c
libcaja-private/caja-search-engine.c
libcaja-private/caja-tree-view-drag-dest.c
src/caja-information-panel.c
src/caja-navigation-action.c
src/caja-navigation-window-pane.c
src/caja-navigation-window-slot.c
src/caja-notebook.c
src/caja-side-pane.c
src/caja-view-as-action.c
src/caja-window-pane.c
src/caja-window-slot.c
src/caja-window.h
src/caja-zoom-action.c

Fixes the warnings:
[caja-Wredundant-decls.txt](https://github.com/mate-desktop/caja/files/3882578/caja-Wredundant-decls.txt)

avoid redundant redeclarations

---

.travis.yml
eel/eel-editable-label.c

more fixes for https://github.com/mate-desktop/caja/issues/1284
Renaming a file can make you crazy without this.
Please test.

editable-label: Don't hyphenate filenames

---

src/caja-navigation-window-menus.c
src/caja-window.c
src/caja-window.h

implement keeping path same as window opening a new window from.
#1335

Implements #1335. Added caja_window_new_window function to caja-window.c to

---

libcaja-private/caja-file-operations.c
src/caja-places-sidebar.c

Both eject device popups were not translatable. Make them translatable.
I also provide a translation into French, but maybe not the best way here since you are using an external tool, but it may still be used as an example…

Translate eject

---

.travis.yml

@yetist 
Anything left for 1.24 branch?

CI: update build environment

---

libcaja-private/caja-file.c

Test: Move a file/folder to trash if empty, next open the trash and check that the Trashed on date is displayed correctly. It requires glib 2.61+ for tests.

caja-file: remove warning GTimeVal is deprecated

---

src/caja-window-slot.c

caja-window-slot: fix window icon replacement/alternation

---

README

Just to help people to not open issue or purpose pull request about translations here...

README.md: Add informations about translation contribution

---

src/file-manager/fm-properties-window.c

closes #1406 
based on https://gitlab.gnome.org/GNOME/nautilus/-/merge_requests/409/diffs

caja properties-window: display dir last modified

---

eel/eel-gtk-extensions.c
eel/eel-gtk-extensions.h
src/caja-file-management-properties.c
src/file-manager/fm-properties-window.c

Based on:
- https://github.com/mate-desktop/mate-terminal/commit/8d2eb0898154f2624e2ae34039169f307a3411a5
- https://github.com/mate-desktop/mate-terminal/commit/622e2d1272bf2d7a99d147482ae6a51b0a77f188

Remove unused variable from eel_notebook_scroll_event_cb

---

src/caja-file-management-properties.ui

caja-file-management-properties: Reduce the height of the dialog

---

src/caja-notebook.c

Based on https://gitlab.gnome.org/GNOME/gnome-terminal/-/blob/887c8128d7c528660afa53fad9ae46e72ca7297c/src/terminal-notebook.c

caja-notebook: Add notebook scroll event

---

libcaja-private/caja-dnd.c

caja-dnd: Create links by default on dnd from Web Browsers

---

src/caja-places-sidebar.c

based on https://github.com/GNOME/nautilus/commit/a73c8c7736cee89bf5470de47aec876b86878bcd
closes #873

caja-places-sidebar: upgrade format drive item

---

data/Makefile.am

Test:
```
$ rpm -qf /usr/bin/msgfmt
gettext-0.21-3.fc33.x86_64
```
```
$ rm -f data/caja-file-management-properties.desktop && make -C data caja-file-management-properties.desktop V=1
make: Entering directory '/home/robert/caja/data'
GETTEXTDATADIR=.. /usr/bin/msgfmt --desktop \
--keyword= --keyword=Name --keyword=GenericName --keyword=Comment --keyword=Keywords \
--template caja-file-management-properties.desktop.in -d ../po -o caja-file-management-properties.desktop
make: Leaving directory '/home/robert/caja/data'
```
```
$ diff ../caja-master/data/caja-file-management-properties.desktop data/caja-file-management-properties.desktop 
1a2,107
> Name[af]=Lêerbestuur
> Name[am]=የ ፋይል አስተዳዳሪ
> Name[ar]=إدارة الملفات
> Name[as]=নথিপত্ৰ ব্যবস্থাপনা
> Name[ast]=Alministración de Ficheros
> …
```

i18n: Fix fetching all keywords on desktop files

---

libcaja-private/caja-file.c

keep one .desktop suffix on desktop file renaming

---

src/caja-places-sidebar.c

https://gitlab.gnome.org/GNOME/gnome-disk-utility/-/commit/9f657153

caja-places-sidebar: gnome-disk-utility ignores the --xid option

---

libcaja-private/caja-file.c

caja-file: Remove unreachable code

---

src/caja-image-properties-page.c

image properties: Improve the layout

---

src/caja-image-properties-page.c

See https://gitlab.gnome.org/GNOME/nautilus/-/commit/7aef6be

image properties: Look for supported mime types at runtime

---

libcaja-private/caja-icon-container.c

Fix https://github.com/mate-desktop/caja/issues/1728 (area near bottom of screen unusable for icon placement)
*revert x11 icon position handling to the older and well tested code 
*use the newer code only in wayland where all the screen can already be used

ensure all of the desktop is usable in x11

---

libcaja-private/caja-file-operations.c

For certain operations, the destination is checked. If an error occurs, the user is asked how to proceed using a dialogue. So far this dialogue was hard-coded to only consider the copy operation.
This fix also considers the other affected operations and generalizes the continue button text.

caja-file-operations: fix caption/button in destination error dialogue
